### ISSUE TITLE
mysql_bytes_received gives invalid number when run

### ISSUE THREAD

**Issue by joakimberglund** [influxdb/telegraf#125]
./telegraf -config telegraf.toml
2015/08/20 13:24:28 Starting Telegraf (version 0.1.5)
2015/08/20 13:24:28 Loaded outputs: influxdb
2015/08/20 13:24:28 Loaded plugins: cpu mysql
2015/08/20 13:24:28 Tags enabled: host=<host>
2015/08/20 13:24:28 Error in plugins: unable to parse 'mysql_bytes_received,host=<host>value=238051953531i': invalid number

But if I run it with -test
./telegraf -config telegraf.toml -test |grep mysql_bytes_received
> [] mysql_bytes_received value=238056088137

everything looks ok.

**Comment by sparrc** [comment]
@joakimberglund, it looks like you're running Influx 0.9.2, please upgrade your influx DB or use Telegraf 0.1.4
