### ISSUE TITLE
telegraf-0.1.6-1.x86_64.rpm

### ISSUE THREAD

**Issue by skynet** [influxdb/telegraf#129]
Any chance someone is going to build the RPM for this:

http://get.influxdb.org/telegraf/telegraf-0.1.6-1.x86_64.rpm

**Comment by sparrc** [comment]
This is my fault, there is a typo in the package name, I'll fix that now, thanks for the report

the actual package is at http://get.influxdb.org/telegraf/telegraf-v0.1.6-1.x86_64.rpm

**Comment by sparrc** [comment]
Thanks much for the issue report!!
