### ISSUE TITLE
mysql config

### ISSUE THREAD

**Issue by skynet** [influxdb/telegraf#130]
Tried different options, but couldn't make it to work:
```
[mysql]
servers = ["127.0.0.1"]
```
Any chance for a better documentation for the configuration of these plugins?

**Comment by joakimberglund** [comment]
This works for me

servers = ["user:password@tcp(<mysqlservername>:3306)/"]

**Comment by skynet** [comment]
That worked for me too. :+1:

**Comment by sparrc** [comment]
This needs to be better documented, thanks for the report

**Comment by sparrc** [comment]
Hi @skynet,

I just took a look at the sample config and actually find some pretty helpful documentation:

```
# Read metrics from one or many mysql servers
[mysql]

# specify servers via a url matching:
#  [username[:password]@][protocol[(address)]]/[?tls=[true|false|skip-verify]]
#  e.g. root:root@http://10.0.0.18/?tls=false
#
# If no servers are specified, then localhost is used as the host.
servers = ["localhost"]
```

Does that cover what you need? This can be viewed by running `telegraf -sample-config`

**Comment by skynet** [comment]
yes, it helps

**Comment by skynet** [comment]
any hint on how do we tag each server? tx

**Comment by sparrc** [comment]
@skynet, that is not supported at the moment, could you open a separate issue for tagging each server with something like a `mysql_server=` tag?

**Comment by skynet** [comment]
Yes, thanks!
