### ISSUE TITLE
Apache server performance plugin

### ISSUE THREAD

**Issue by skynet** [influxdb/telegraf#132]
Quite interesting to notice (by looking for, and not finding it) that no one has built an apache plugin for telegraf, so far. (Apache mod_status documentation: http://httpd.apache.org/docs/2.4/mod/mod_status.html)

Or maybe I am just mistaken?

**Comment by skynet** [comment]
Is it possible to add a plugin after installing telegraf (from rpm)

**Comment by sparrc** [comment]
I don't think a plugin could be added after installing from rpm, you would need to build from source

**Comment by skynet** [comment]
Which is a serious drawback. Even building the rpm lacks some helpful documentation. I wanted to contribute.

**Comment by sparrc** [comment]
I'm not sure I understand how you would expect to do that, the RPM ships with a pre-built binary, there is no possible way that we could support adding plugins to a binary without having the telegraf agent built from a separate repo as the plugins, which I think is an unecessary complication.

As for the RPM documentation, what would you like to see? I was thinking I should add the location of the binary and config file?

**Comment by skynet** [comment]
You did actually provide the documentation on how to build telegraf and that's good enough for now. I'd like to see more plugins being submitted. The problem is that they all need to end up compiled at the same time with telegraf and at one point or another you will not be able to accept all pull requests. But it makes perfect sense to go with this philosophy and foundation. Maybe an automated method for customizing the build would help. Similar to how Twitter Bootstrap is built: http://getbootstrap.com/customize/

**Comment by sparrc** [comment]
That's pretty cool! I could imagine something like that for selecting plugins and outputs :+1:

**Comment by KPACHbIuLLIAnO4** [comment]
Recently i've implemented simple apache performance plugin, you can find it in my fork of telegraf repo. You can use it if you find it useable.

**Comment by skynet** [comment]
:+1:

**Comment by skynet** [comment]
Tested and it works. @KPACHbIuLLIAnO4 can you do a pull request here?

**Comment by sparrc** [comment]
+1, @KPACHbIuLLIAnO4 can you please re-open your pull request? I would like to get an Apache plugin merged into main

**Comment by KPACHbIuLLIAnO4** [comment]
I was going to prepare a new branch with apache plugin only, beacuse I have
some fixes in master that you probably don't want to merge...

2015-08-31 18:51 GMT+03:00 Cameron Sparr <notifications@github.com>:

**Comment by KPACHbIuLLIAnO4** [comment]
Created pull request

2015-08-31 19:00 GMT+03:00 Alexander Oleinik <oaev.oaev@gmail.com>:
