### ISSUE TITLE
Issues on Installing telegraf_v0.1.6_amd64 on trusty

### ISSUE THREAD

**Issue by rplessl** [influxdb/telegraf#134]
There is an error in the newest debian package.

```
dpkg: error processing archive /var/cache/apt/archives/telegraf_v0.1.6_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'telegraf':
 error in 'Version' field string 'v0.1.6': version number does not start with digit
```

The Version tag must be a digit according to 
   https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version

**Comment by sparrc** [comment]
Thanks for the report, I will fix this

**Comment by sparrc** [comment]
This should now be fixed, please try again with the new link on the README: http://get.influxdb.org/telegraf/telegraf_0.1.6_amd64.deb

thanks again for the issue report!
