### ISSUE TITLE
MQTT Plugin

### ISSUE THREAD

**Issue by sparrc** [influxdb/telegraf#135]

**Comment by rapport** [comment]
I think this is important too. I am using this currently https://github.com/jpmens/mqttcollect but suspect it won't scale up.

**Comment by rapport** [comment]
This looks like It may work https://eclipse.org/paho/clients/golang/. Would it be possible to write a telegraf to use this and if so would you have time to do this or can you help me get started and I will have a go?

**Comment by sparrc** [comment]
@rapport, at the moment I don't have the time, but always willing to help with Pull Requests :-)

**Comment by markfink** [comment]
I could add that but I do not know telegraf. When I looked into influxdb a few weeks before I did not notice it. Is telegraf the a new way of adding data? How about a mqtt plugin for influxdb?

**Comment by sparrc** [comment]
@markfink telegraf is a daemon for collecting data and outputting it into InfluxDB, although it supports other output types as well

**Comment by rummand** [comment]
Would love the MQTT support, so it's +1 from me...

**Comment by sparrc** [comment]
closed by #241
