### ISSUE TITLE
Build Telegraf from source

### ISSUE THREAD

**Issue by skynet** [influxdb/telegraf#141]
What's the proper way to build Telegraf from source. You've made some changes recently and I need to use them before next release. Besides, I would like to give it a try at building plugins.

**Comment by sparrc** [comment]
There is a section in the README about this: https://github.com/influxdb/telegraf#from-source

The Makefile assumes that you have golang installed and your GOPATH setup, see here: https://golang.org/doc/code.html#GOPATH for GOPATH instructions.

let me know if you need additional info!

**Comment by sparrc** [comment]
although I just realized I didn't put the 1st step in the README, which is to run `go get github.com/influxdb/telegraf`, I'll add that
