### ISSUE TITLE
Add InfluxDB clustering support

### ISSUE THREAD

**Issue by panda87** [influxdb/telegraf#143]
Hi

In telegraf conf file there is an option to put only one address.
But, in case out outage of the leader instance the telegraf clients will get an error.

It seems that the simple workaround will be the ability to put a list of possible instances in the url parameter and if the first instance get timeout (with the existing param) this will move forward to the second instance and so on.

What do you think?

**Comment by sparrc** [comment]
:+1: I think this is a good idea
