### ISSUE TITLE
Elasticsearch and RabbitMQ Https Support

### ISSUE THREAD

**Issue by Madhu1512** [influxdb/telegraf#148]
Is there any plan to support Https  for RabbitMQ Plugin?.

**Comment by sparrc** [comment]
have you tried using an https url? I don't see why this wouldn't work. If it's not working, please include the error that you're getting

**Comment by Madhu1512** [comment]
if you the url with signed certificate, then the plugin won't work.

Here is  the message i am getting 

x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: algorithm unimplemented" while trying to verify candidate authority certificate

**Comment by sparrc** [comment]
@Madhu1512 what is your OS and what version of telegraf are you running? and where are you seeing this error message, in the output of telegraf -debug?

**Comment by sparrc** [comment]
@Madhu1512 I'm going to assume your problem was solved, please re-open if you're able to provide more information, thank you!
