### ISSUE TITLE
Un-used data in InfluxDB

### ISSUE THREAD

**Issue by skynet** [influxdb/telegraf#157]
The accumulated data in InfluxDB goes way beyond acceptable limits when multiple plugins enabled. Seen over 2.8GB of telegraf database in just a couple of days. We use only a selected set of fields from each measurement and don't really need all the other fields sent for storage to InfluxDB. Is it possible to select certain fields for a plugin and have only those fields recorded in InfluxDB? Under the same circumstances, is it possible to record less points per hour?

**Comment by sparrc** [comment]
https://github.com/influxdb/telegraf#plugin-options

there are options for passing and dropping metrics, as well as collection intervals

**Comment by skynet** [comment]
This really helps, thank you!
