### ISSUE TITLE
Yum and Apt repositories for Telegraf

### ISSUE THREAD

**Issue by skynet** [influxdb/telegraf#160]
Would it be possible to setup a yum repo for this project, something like this:

```
[telegraf]
name=telegraf
baseurl=https://packagecloud.io/telegraf/stable/el/6/$basearch
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packagecloud.io/gpg.key https://telegraf.s3.amazonaws.com/RPM-GPG-KEY-telegraf
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
```

That way we don't have to check for a new release, download and run the upgrade manually.

**Comment by sparrc** [comment]
I agree, and am also going to include Apt repos while we're at it. Should be able to use something like packagecloud or bintray to host this for us, thanks for your suggestion!

**Comment by kokarn** [comment]
This would help greatly with updating on multiple servers :+1:

**Comment by skynet** [comment]
Is the new release imminent?

**Comment by kokarn** [comment]
Well 3 releases in August and 2 in September is a bit of work if you have a few servers :)

**Comment by skynet** [comment]
Not if telegraf updates with yum, right?

**Comment by kokarn** [comment]
Yeah, if they add yum and apt it would be easy as pie :cake:

**Comment by skynet** [comment]
Except that Telegraf is so much dependent on InfluxDB, which is not yet updatable using yum, plus that InfluxDB is going through heavy changes with broken compatibility from one version to another. Hope that all of this will get stable one day, before we get tired of running into problems with the updates.

**Comment by skynet** [comment]
Any news about this? I'd so much like to just have it updated along with other libraries.

**Comment by rossmcdonald** [comment]
@skynet No update yet. We should have progress made on this sometime this week, though. I'll send out an update as soon as it's been added.

**Comment by skynet** [comment]
any luck on this?

**Comment by skynet** [comment]
Just noticed that influxdb provides telegraf packages:

```
yum provides telegraf
Loaded plugins: priorities, update-motd, upgrade-helper
572 packages excluded due to repository priority protections
telegraf-0.2.0-1.x86_64 : InfluxDB Telegraf agent
Repo        : influxdb



telegraf-0.2.4-1.x86_64 : InfluxDB Telegraf agent
Repo        : influxdb



telegraf-0.2.4-1.x86_64 : InfluxDB Telegraf agent
Repo        : @influxdb
```

**Comment by rossmcdonald** [comment]
@skynet Yes, sorry for not updating this. Telegraf packages are now officially available through the repos.influxdata.com repository. Let me know if anyone runs into any issues!

**Comment by sparrc** [comment]
thanks much @rossmcdonald
