### ISSUE TITLE
Which version of mongodb supported?

### ISSUE THREAD

**Issue by panqiushi** [influxdb/telegraf#161]
I'm using mongodb 2.4.6, but there is no metrics data for mongodb, other plugins works fine. And I'm useing telegraf 0.1.7

**Comment by sparrc** [comment]
Could you provide more details? Useful would be the telegraf command you're running, and also include some output using the `-test` and `-debug` flags

**Comment by sparrc** [comment]
closing this in absence of more info, please re-open if not fixed

**Comment by xluffy** [comment]
I have same issue. When i run `-test`, no metric data for mongodb.

![4d47c5c370b9a12e70a4478a195024fe](https://cloud.githubusercontent.com/assets/1505720/24496346/3218b96e-1562-11e7-9d17-baa113a02e36.png)

Telegraf version: telegraf-1.2.1-1
MongoDB version: 3.0.6

Telegraf config:

```
[global_tags]
  dc = "ap-northeast-1"
  rack = "1a"

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"]
  database = "telegraf"
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s
```

mongodb.conf

```
[[inputs.mongodb]]
  servers = ["127.0.0.1:27017"]
  gather_perdb_stats = true
```

**Comment by xluffy** [comment]
I check in InfluxDB, have data send from telegraf agent mongodb. Only have a problem, `-test` don't show any data metric.

**Comment by danielnelson** [comment]
@xluffy I see that too with 1.2.1, but it appears to be fixed on master.  Only difference is if I use your server option I get:
```
Unable to parse to address '127.0.0.1:27017': parse 127.0.0.1:27017: first path segment in URL cannot contain colon
```

Instead I'm testing with "mongo://127.0.0.1:27017".

**Comment by xluffy** [comment]
@danielnelson: Thanks for replying. Now, It's work fine. I saw data metric in InfluxDB. But it still doesn't show metric when use `-test` or `-debug`. Is this a bug?

![b1c7b3b42712874843dc57e310daa281](https://cloud.githubusercontent.com/assets/1505720/24531960/f949e5e2-15e6-11e7-8b16-7eec39a33e56.png)

**Comment by danielnelson** [comment]
`-test` only runs the inputs, but debug alone shouldn't change anything other than the logging.
