### ISSUE TITLE
[0.1.8] .deb package does not support systemd

### ISSUE THREAD

**Issue by beckettsean** [influxdb/telegraf#170]
```
root@sean-15:~# sudo service telegraf start
Failed to start telegraf.service: Unit telegraf.service failed to load: No such file or directory.
```

Note that `/etc/init.d/telegraf start` works fine.

See https://github.com/influxdb/influxdb/issues/3989 for details.

**Comment by sparrc** [comment]
Looks like our packaging script is upstart-specific, we'll need to update for systemd

**Comment by sparrc** [comment]
Also put brief instructions for stopping/starting the service and the location of the configuration file

**Comment by sparrc** [comment]
this has been taken care of in the previously mentioned commits
