### ISSUE TITLE
Remind users of installation and start/stop instructions for package installers

### ISSUE THREAD

**Issue by grempe** [influxdb/telegraf#172]
README enhancement needed.

e.g. for Ubuntu

wget http://get.influxdb.org/telegraf/telegraf_0.1.8_amd64.deb
dpkg -i telegraf_0.1.8_amd64.deb

# see issue #170 
/etc/init.d/telegraf start

**Comment by sparrc** [comment]
I'm closing this because I'll just track it in issue #170
