### ISSUE TITLE
Wrong timestamps with mongodb plugin

### ISSUE THREAD

**Issue by Pomyk** [influxdb/telegraf#175]
I have set the precision to seconds. Mongodb plugin writes timestamp in nanoseconds without respecting the precision.
Influxdb then reads this and gets year 2111 (that causes some strange behavior - a new WAL after every write).

**Comment by sparrc** [comment]
You'll need to be more specific, things to include:

1. operating system
2. config file
3. version number
4. debug output

My first guess is that there is something wrong with your system's clock, I don't know how else to explain year 2111

**Comment by sparrc** [comment]
I still don't understand the part about year 2111, but I have found a bug in setting the precision for the plugin gathering in certain situations. I will have a fix for that soon.

**Comment by Pomyk** [comment]
Thanks for the quick response, but that didn't fix it unfortunately.
1. os - CentOS 7
2. relevant config part is:
```
[agent]
  precision = "s"
[mongodb]
```

3. influx and telegraf compiled from master
4. output from influxd: https://gist.github.com/Pomyk/d7c707ec9432dda8cdb3

From the Line protocol docs:

"Timestamps are assumed to be in nanoseconds unless a precision value is passed in the query string."

Telegraf passes precision=s in params, but data from mongodb plugin has timestamps encoded in nanoseconds. Influxdb reads ns and multiplies by 1000000 so the timestamp overflows and the date becomes random.

**Comment by sparrc** [comment]
Okay, thanks for the info, I'll have to look into this next week. Can you please provide the debug telegraf output? and also the output of telegraf -version (if this doesn't return anything, include the commit from which you built.)

**Comment by Pomyk** [comment]
Version v0.1.8-11-gd8482cc
Debug output: https://gist.github.com/Pomyk/a2929f84882b65b28622

**Comment by sparrc** [comment]
I've reproduced this, working on a fix now

**Comment by sparrc** [comment]
@Pomyk wow this turned into a rabbit-hole, and actually looks like it is a bug in influxfb. I have a PR up against the InfluxDB client code (https://github.com/influxdb/influxdb/pull/4099) to fix this and will have a separate PR for telegraf sometime tomorrow.
