### ISSUE TITLE
Tags no longer passed in due to change in Client

### ISSUE THREAD

**Issue by shortjared** [influxdb/telegraf#18]
I was experimenting with Telegraf, and I am pretty impressed with the ease of getting it setup and the potential for adding plugins. That said, I noticed that Tags don't seem to be passed at the point level.  Not even the default "host" as I would have expected after finding issue #4 .

I think I tracked down the cause.

It looks like a recent change in the influxdb client ( https://github.com/influxdb/influxdb/commit/e6c36d5e4480334f59cd71088577fb931916094c ) has made it so that passing common parameters at the batch level is no longer allowed.

If we look at the [agent.go code](https://github.com/influxdb/telegraf/blob/3a430420898ab2df707dd037bfaf220ac5d583d2/agent.go#L109-L149), it appears that the "Tags" were passed at the top of the batch level and expected to be inherited down through the "sub" points. This seems to be leveraging the now removed common batch parameters functionality.

```Go
	close(points)

	var acc BatchPoints
	acc.Tags = a.Config.Tags
	acc.Time = time.Now()
	acc.Database = a.Config.Database

	for sub := range points {
		acc.Points = append(acc.Points, sub.Points...)
	}
```

I am not familiar enough with Go to effectively fix and properly add unit testing, but hopefully this is enough for someone to jump in and take it from here.

**Comment by dever860** [comment]
+1

**Comment by mgresser** [comment]
+1 Also seeing this issue.
