### ISSUE TITLE
Issues when specifying multiple rabbitmq cluster

### ISSUE THREAD

**Issue by rvrignaud** [influxdb/telegraf#183]
Hello,

I'm trying to use rabbitmq plugin with multiple rabbitmq clusters.
It seems (I may be wrong) that some metrics are not tagged with a specific cluster like rabbitmq_messages, rabbitmq_messages_ready, etc ...
When I try to display graph with grafana I get the data mixed in the same graph without the possibility to filter between the clusters.
Would that be possible to add a cluster name configuration ?

**Comment by sparrc** [comment]
That's a good idea, and should be a simple fix, thanks for the suggestion!
