### ISSUE TITLE
Support include directory for configuration files

### ISSUE THREAD

**Issue by rvrignaud** [influxdb/telegraf#184]
Hello, 
It would make things much more easier if telegraf could support an include directive for the configuration (like /etc/opt/telegraf/conf.d).
This would be much more easier to use to enable plugins with configuration management systems or on docker.

Thoughts ?

**Comment by sparrc** [comment]
That's a good idea, but do you mean an include "directory" where individual files could add plugins to telegraf? Similar to how `/etc/apt/sources.list.d` works on ubuntu?

**Comment by rvrignaud** [comment]
Yes that's what I'm talking about. A directory where every file with a specific extension (like *.conf) could append configuration

**Comment by sparrc** [comment]
cool, that sounds like a good idea

**Comment by dj-wasabi** [comment]
Yes, this would be an very nice to have. This is very handy when you use tools like Ansible or Puppet for installing/configuring servers, each role or module wil install their own telegraf configuration file in this directory.

**Comment by descrepes** [comment]
Hi,

Any updates on this feature ?
I'm actually managing Telegraf in puppet with augeas which is a nightmare :)
This feature will really improve the deployment of Telegraf :p 

Thx for the awesome work !

**Comment by sparrc** [comment]
Right now I'm focused on statsd support, I'm not sure how soon I'll be able to get to this, if someone could help out on this one with a PR it would be much appreciated!

**Comment by gotyaoi** [comment]
I'm sort of looking at doing this, but there's a slight hitch. My inclination is that values from included configs should override higher level values, but since the config struct holds the data as "ast.Table"s, merging them is a little difficult. I can see a couple places using UnmarshalTable on them for convenience, but aside from that, is there a reason they're being stored like that?

**Comment by sparrc** [comment]
@gotyaoi not that I'm aware of, I think you could refactor out the `ast.Table`'s. That would be really awesome because it would make that code more readable too.

**Comment by gotyaoi** [comment]
Ok, I'll work on that then.

**Comment by gotyaoi** [comment]
Small status update. Wasn't able to get rid of the `ast.Table`s entirely, as they're the dynamic part needed to account for loading data into structs which aren't known about ahead of time. Focused on getting the data out of the `ast.Table`s and into the actual structs as soon as possible.

Implemented a very basic struct merge function. Useful for setting defaults in a base struct, then overriding them later with an overlay struct. It operates on any fields that were set in the base struct, even if they were set to the zero value. Any regular values in the base struct are overwritten, while arrays are appended to. To know which fields were set in the overlay struct, I kept around a list of fields gleaned from the ast. A possible issue is that these fields are as in the toml, which is not necessarily the same as the name in the struct. There's some fuzzy matching that accounts for case changes and the addition of underscores, but if the `toml:` tag is significantly different than the struct field name, it will miss.

Currently the existing tests are passing. Going over them to determine if they are still applicable to the changed code, or if they need to be altered or added to.

You can take a look at the progress so far in my fork, in the branch config_directory: https://github.com/gotyaoi/telegraf/tree/config_directory

Odd issue, when rewriting the PluginsDeclared and OutputsDeclared function, I wasn't able to find a way to generically get the keys of any array, so those two functions have some duplicated code. Could just be me being noobish, so advice appreciated. https://github.com/gotyaoi/telegraf/blob/config_directory/config.go#L170

**Comment by gotyaoi** [comment]
Ok, I've got some tests in and implemented directory loading. I'll probably try to run this myself for a little bit, then open a PR.

**Comment by gotyaoi** [comment]
PR open here: https://github.com/influxdb/telegraf/pull/295

**Comment by gotyaoi** [comment]
This has been merged, so it can probably be closed now. I think I messed up the issue number on the commit, so it didn't auto close.

**Comment by sparrc** [comment]
thanks much @gotyaoi :+1:
