### ISSUE TITLE
Support per queue metrics for rabbitmq plugins

### ISSUE THREAD

**Issue by rvrignaud** [influxdb/telegraf#185]
Hello,

This would be awesome if telegraf could support per queues metrics.
Collectd has a pretty exhaustive plugin here : https://github.com/NYTimes/collectd-rabbitmq

Thoughts ?

**Comment by sparrc** [comment]
thanks for the suggestion, that'll be a good enhancement

**Comment by ekini** [comment]
I'm working on it.

**Comment by rvrignaud** [comment]
Thanks @ekini !

**Comment by rvrignaud** [comment]
Hello @ekini, is there anything to test ? How can I help you ?

**Comment by ekini** [comment]
Sorry to make you waiting for it so long. I've created the pull request.
