### ISSUE TITLE
EL5 support

### ISSUE THREAD

**Issue by mgresser** [influxdb/telegraf#186]
The current RPM doesn't install cleanly on EL5 systems like CentOS 5.

The first issue is the init script doesn't support chkconfig. It needs a pair of lines along the lines of this at the top of the init script in order to start up properly in EL5.
```
# chkconfig: 2345 99 01
# description: Telegraf daemon
```
Secondly the rpm adds the telegraph user with the flag --system instead of the -r flag that is expected.

**Comment by sparrc** [comment]
I'm assuming you're talking about RHEL 5?

**Comment by mgresser** [comment]
RHEL5, CentOS5 or Scientific Linux5 all would show this I believe.

**Comment by sparrc** [comment]
okay, thank you for the report! I'll try to get to this today or tomorrow

**Comment by sparrc** [comment]
@mgresser I've gotten distracted by other things, if you know what the solution is here, do you mind submitting a PR to fix this?
