### ISSUE TITLE
httpjson plugin should allow JSON to add tags

### ISSUE THREAD

**Issue by abh** [influxdb/telegraf#190]
The httpjson plugin should have a way for the data emitter/end-point to specify tags to add to each key/value pair. This would make it possible to make "InfluxDB-aware" (telegraf-aware, I guess to be exact) applications and just use this plugin, rather than having to make a specific plugin for each application.

**Comment by sparrc** [comment]
that sounds like a good idea :+1:

**Comment by sparrc** [comment]
Closing this in favor of https://github.com/influxdb/telegraf/issues/277, @abh let me know what you think of what I proposed in that case
