### ISSUE TITLE
HAProxy 5xx stats missing

### ISSUE THREAD

**Issue by nckturner** [influxdb/telegraf#194]
HAProxy plugin leaves out 5xx stats.  

Looks like the case `HF_HRSP_5xx` in `importCsvResult()` is missing.

**Comment by sparrc** [comment]
Thanks for the report! Sounds like a pretty simple fix, would you like to submit a PR? Otherwise I may be able to get to this tomorrow

**Comment by nckturner** [comment]
Yeah, I'll submit one tonight.
