### ISSUE TITLE
Invalid number error in all plugins except CPU and System on Ubuntu 14.04

### ISSUE THREAD

**Issue by vhajdari** [influxdb/telegraf#195]
Running telegraf on Ubuntu 14.04 inside of VMWare produces invalid number error when plugins other than cpu and/or system are enabled.

Config and debug output follows:

Running in VMWare Fusion 6.0.6
```
on@foobuntu:/opt/telegraf$ uname -a
Linux foobuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
# Telegraf configuration
```
[tags]
    cluster = "cdh-5.4"
[agent]
    interval = "5s"
    debug = true
[outputs]
[outputs.influxdb]
    url = "http://localhost:8086"
    database = "acm"

# PLUGINS
[cpu]
    percpu = true
    totalcpu = true
[disk]
[io]
[mem]
[system]
[swap]
```
# Output 
on@foobuntu:/opt/telegraf$ ./telegraf -config /etc/opt/telegraf/telegraf.conf
2015/08/29 13:03:28 Starting Telegraf (version 0.1.8)
2015/08/29 13:03:28 Loaded outputs: influxdb
2015/08/29 13:03:28 Loaded plugins: cpu disk io mem swap system
2015/08/29 13:03:28 Tags enabled: host=foobuntu
2015/08/29 13:03:28 Error in output [influxdb]: unable to parse 'disk_total,fstype=ext4,host=foobuntu,path=/ value=19674116096i': invalid number
2015/08/29 13:03:28 Error encountered flushing outputs

# Output w/ Debug = true
on@foobuntu:/opt/telegraf$ sudo ./telegraf -config /etc/opt/telegraf/telegraf.conf
2015/08/29 13:16:29 Successfully connected to output: influxdb
2015/08/29 13:16:29 Starting Telegraf (version 0.1.8)
2015/08/29 13:16:29 Loaded outputs: influxdb
2015/08/29 13:16:29 Loaded plugins: cpu disk io mem swap system
2015/08/29 13:16:29 Debug: enabled
2015/08/29 13:16:29 Agent Config: Interval:5s, Debug:true, Hostname:"foobuntu", Precision:"s", UTC: true
2015/08/29 13:16:29 Tags enabled: cluster=cdh-5.4 host=foobuntu
> [cpu="cpu0"] cpu_user value=1063.14
> [cpu="cpu0"] cpu_system value=313.71
> [cpu="cpu0"] cpu_idle value=217645.17
> [cpu="cpu0"] cpu_nice value=149.45
> [cpu="cpu0"] cpu_iowait value=13.13
> [cpu="cpu0"] cpu_irq value=0.02
> [cpu="cpu0"] cpu_softirq value=35.88
> [cpu="cpu0"] cpu_steal value=0
> [cpu="cpu0"] cpu_guest value=0
> [cpu="cpu0"] cpu_guestNice value=0
> [cpu="cpu0"] cpu_stolen value=0
> [cpu="cpu0"] cpu_busy value=1575.3300000000004
> [cpu="cpu-total"] cpu_user value=1063.14
> [cpu="cpu-total"] cpu_system value=313.71
> [cpu="cpu-total"] cpu_idle value=217645.17
> [cpu="cpu-total"] cpu_nice value=149.45
> [cpu="cpu-total"] cpu_iowait value=13.13
> [cpu="cpu-total"] cpu_irq value=0.02
> [cpu="cpu-total"] cpu_softirq value=35.88
> [cpu="cpu-total"] cpu_steal value=0
> [cpu="cpu-total"] cpu_guest value=0
> [cpu="cpu-total"] cpu_guestNice value=0
> [cpu="cpu-total"] cpu_stolen value=0
> [cpu="cpu-total"] cpu_busy value=1575.3300000000004
> [fstype="ext4" path="/"] disk_total value=19674116096
> [fstype="ext4" path="/"] disk_free value=17065168896
> [fstype="ext4" path="/"] disk_used value=2608947200
> [fstype="ext4" path="/"] disk_inodes_total value=1228800
> [fstype="ext4" path="/"] disk_inodes_free value=1099007
> [fstype="ext4" path="/"] disk_inodes_used value=129793
> [fstype="proc" path="/proc"] disk_total value=0
> [fstype="proc" path="/proc"] disk_free value=0
> [fstype="proc" path="/proc"] disk_used value=0
> [fstype="proc" path="/proc"] disk_inodes_total value=0
> [fstype="proc" path="/proc"] disk_inodes_free value=0
> [fstype="proc" path="/proc"] disk_inodes_used value=0
> [fstype="sysfs" path="/sys"] disk_total value=0
> [fstype="sysfs" path="/sys"] disk_free value=0
> [fstype="sysfs" path="/sys"] disk_used value=0
> [fstype="sysfs" path="/sys"] disk_inodes_total value=0
> [fstype="sysfs" path="/sys"] disk_inodes_free value=0
> [fstype="sysfs" path="/sys"] disk_inodes_used value=0
> [fstype="tmpfs" path="/sys/fs/cgroup"] disk_total value=4096
> [fstype="tmpfs" path="/sys/fs/cgroup"] disk_free value=4096
> [fstype="tmpfs" path="/sys/fs/cgroup"] disk_used value=0
> [fstype="tmpfs" path="/sys/fs/cgroup"] disk_inodes_total value=126302
> [fstype="tmpfs" path="/sys/fs/cgroup"] disk_inodes_free value=126289
> [fstype="tmpfs" path="/sys/fs/cgroup"] disk_inodes_used value=13
> [fstype="fusectl" path="/sys/fs/fuse/connections"] disk_total value=0
> [fstype="fusectl" path="/sys/fs/fuse/connections"] disk_free value=0
> [fstype="fusectl" path="/sys/fs/fuse/connections"] disk_used value=0
> [fstype="fusectl" path="/sys/fs/fuse/connections"] disk_inodes_total value=0
> [fstype="fusectl" path="/sys/fs/fuse/connections"] disk_inodes_free value=0
> [fstype="fusectl" path="/sys/fs/fuse/connections"] disk_inodes_used value=0
> [fstype="debugfs" path="/sys/kernel/debug"] disk_total value=0
> [fstype="debugfs" path="/sys/kernel/debug"] disk_free value=0
> [fstype="debugfs" path="/sys/kernel/debug"] disk_used value=0
> [fstype="debugfs" path="/sys/kernel/debug"] disk_inodes_total value=0
> [fstype="debugfs" path="/sys/kernel/debug"] disk_inodes_free value=0
> [fstype="debugfs" path="/sys/kernel/debug"] disk_inodes_used value=0
> [fstype="securityfs" path="/sys/kernel/security"] disk_total value=0
> [fstype="securityfs" path="/sys/kernel/security"] disk_free value=0
> [fstype="securityfs" path="/sys/kernel/security"] disk_used value=0
> [fstype="securityfs" path="/sys/kernel/security"] disk_inodes_total value=0
> [fstype="securityfs" path="/sys/kernel/security"] disk_inodes_free value=0
> [fstype="securityfs" path="/sys/kernel/security"] disk_inodes_used value=0
> [fstype="devtmpfs" path="/dev"] disk_total value=505901056
> [fstype="devtmpfs" path="/dev"] disk_free value=505888768
> [fstype="devtmpfs" path="/dev"] disk_used value=12288
> [fstype="devtmpfs" path="/dev"] disk_inodes_total value=123511
> [fstype="devtmpfs" path="/dev"] disk_inodes_free value=123018
> [fstype="devtmpfs" path="/dev"] disk_inodes_used value=493
> [fstype="devpts" path="/dev/pts"] disk_total value=0
> [fstype="devpts" path="/dev/pts"] disk_free value=0
> [fstype="devpts" path="/dev/pts"] disk_used value=0
> [fstype="devpts" path="/dev/pts"] disk_inodes_total value=0
> [fstype="devpts" path="/dev/pts"] disk_inodes_free value=0
> [fstype="devpts" path="/dev/pts"] disk_inodes_used value=0
> [fstype="tmpfs" path="/run"] disk_total value=103469056
> [fstype="tmpfs" path="/run"] disk_free value=102391808
> [fstype="tmpfs" path="/run"] disk_used value=1077248
> [fstype="tmpfs" path="/run"] disk_inodes_total value=126302
> [fstype="tmpfs" path="/run"] disk_inodes_free value=125723
> [fstype="tmpfs" path="/run"] disk_inodes_used value=579
> [fstype="tmpfs" path="/run/lock"] disk_total value=5242880
> [fstype="tmpfs" path="/run/lock"] disk_free value=5242880
> [fstype="tmpfs" path="/run/lock"] disk_used value=0
> [fstype="tmpfs" path="/run/lock"] disk_inodes_total value=126302
> [fstype="tmpfs" path="/run/lock"] disk_inodes_free value=126300
> [fstype="tmpfs" path="/run/lock"] disk_inodes_used value=2
> [fstype="tmpfs" path="/run/shm"] disk_total value=517332992
> [fstype="tmpfs" path="/run/shm"] disk_free value=517332992
> [fstype="tmpfs" path="/run/shm"] disk_used value=0
> [fstype="tmpfs" path="/run/shm"] disk_inodes_total value=126302
> [fstype="tmpfs" path="/run/shm"] disk_inodes_free value=126301
> [fstype="tmpfs" path="/run/shm"] disk_inodes_used value=1
> [fstype="tmpfs" path="/run/user"] disk_total value=104857600
> [fstype="tmpfs" path="/run/user"] disk_free value=104857600
> [fstype="tmpfs" path="/run/user"] disk_used value=0
> [fstype="tmpfs" path="/run/user"] disk_inodes_total value=126302
> [fstype="tmpfs" path="/run/user"] disk_inodes_free value=126299
> [fstype="tmpfs" path="/run/user"] disk_inodes_used value=3
> [fstype="pstore" path="/sys/fs/pstore"] disk_total value=0
> [fstype="pstore" path="/sys/fs/pstore"] disk_free value=0
> [fstype="pstore" path="/sys/fs/pstore"] disk_used value=0
> [fstype="pstore" path="/sys/fs/pstore"] disk_inodes_total value=0
> [fstype="pstore" path="/sys/fs/pstore"] disk_inodes_free value=0
> [fstype="pstore" path="/sys/fs/pstore"] disk_inodes_used value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpuset"] disk_total value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpuset"] disk_free value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpuset"] disk_used value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpuset"] disk_inodes_total value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpuset"] disk_inodes_free value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpuset"] disk_inodes_used value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpu"] disk_total value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpu"] disk_free value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpu"] disk_used value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpu"] disk_inodes_total value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpu"] disk_inodes_free value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpu"] disk_inodes_used value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpuacct"] disk_total value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpuacct"] disk_free value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpuacct"] disk_used value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpuacct"] disk_inodes_total value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpuacct"] disk_inodes_free value=0
> [fstype="cgroup" path="/sys/fs/cgroup/cpuacct"] disk_inodes_used value=0
> [fstype="cgroup" path="/sys/fs/cgroup/memory"] disk_total value=0
> [fstype="cgroup" path="/sys/fs/cgroup/memory"] disk_free value=0
> [fstype="cgroup" path="/sys/fs/cgroup/memory"] disk_used value=0
> [fstype="cgroup" path="/sys/fs/cgroup/memory"] disk_inodes_total value=0
> [fstype="cgroup" path="/sys/fs/cgroup/memory"] disk_inodes_free value=0
> [fstype="cgroup" path="/sys/fs/cgroup/memory"] disk_inodes_used value=0
> [fstype="ext2" path="/boot"] disk_total value=246755328
> [fstype="ext2" path="/boot"] disk_free value=175990784
> [fstype="ext2" path="/boot"] disk_used value=70764544
> [fstype="ext2" path="/boot"] disk_inodes_total value=62248
> [fstype="ext2" path="/boot"] disk_inodes_free value=61942
> [fstype="ext2" path="/boot"] disk_inodes_used value=306
> [fstype="cgroup" path="/sys/fs/cgroup/systemd"] disk_total value=0
> [fstype="cgroup" path="/sys/fs/cgroup/systemd"] disk_free value=0
> [fstype="cgroup" path="/sys/fs/cgroup/systemd"] disk_used value=0
> [fstype="cgroup" path="/sys/fs/cgroup/systemd"] disk_inodes_total value=0
> [fstype="cgroup" path="/sys/fs/cgroup/systemd"] disk_inodes_free value=0
> [fstype="cgroup" path="/sys/fs/cgroup/systemd"] disk_inodes_used value=0
> [] mem_total value=1034670080
> [] swap_total value=1069543424
> [] swap_used value=7176192
> [] swap_free value=1062367232
> [] swap_used_perc value=0.6709584518935812
> [] swap_in value=5648384
> [] swap_out value=13959168
> [] system_load1 value=0
> [] system_load5 value=0.01
> [] system_load15 value=0.05
> [] system_uptime value=220154
> [] system_uptime_format value=2 days, 13:09
> [] mem_available value=665194496
> [] mem_used value=713244672
> [] mem_used_perc value=35.70950693770907
> [] mem_free value=321425408
> [] mem_active value=289820672
> [] mem_inactive value=229052416
> [] mem_buffers value=29315072
> [] mem_cached value=314454016
> [] mem_wired value=0
> [] mem_shared value=0
> [name="sda"] io_reads value=74564
> [name="sda"] io_writes value=520631
> [name="sda"] io_read_bytes value=1383047168
> [name="sda"] io_write_bytes value=5568548864
> [name="sda"] io_read_time value=30848
> [name="sda"] io_write_time value=249288
> [name="sda"] io_io_time value=117104
> [name="sda1"] io_reads value=841
> [name="sda1"] io_writes value=285
> [name="sda1"] io_read_bytes value=6882304
> [name="sda1"] io_write_bytes value=72871936
> [name="sda1"] io_read_time value=124
> [name="sda1"] io_write_time value=436
> [name="sda1"] io_io_time value=180
> [name="sda2"] io_reads value=2
> [name="sda2"] io_writes value=0
> [name="sda2"] io_read_bytes value=2048
> [name="sda2"] io_write_bytes value=0
> [name="sda2"] io_read_time value=0
> [name="sda2"] io_write_time value=0
> [name="sda2"] io_io_time value=0
> [name="sda5"] io_reads value=73104
> [name="sda5"] io_writes value=520346
> [name="sda5"] io_read_bytes value=1365009408
> [name="sda5"] io_write_bytes value=5495676928
> [name="sda5"] io_read_time value=30656
> [name="sda5"] io_write_time value=248852
> [name="sda5"] io_io_time value=116884
> [name="dm-0"] io_reads value=70625
> [name="dm-0"] io_writes value=692746
> [name="dm-0"] io_read_bytes value=1335034880
> [name="dm-0"] io_write_bytes value=5481717760
> [name="dm-0"] io_read_time value=30136
> [name="dm-0"] io_write_time value=422108
> [name="dm-0"] io_io_time value=115548
> [name="dm-1"] io_reads value=1873
> [name="dm-1"] io_writes value=3408
> [name="dm-1"] io_read_bytes value=7671808
> [name="dm-1"] io_write_bytes value=13959168
> [name="dm-1"] io_read_time value=748
> [name="dm-1"] io_write_time value=24780
> [name="dm-1"] io_io_time value=1556
> [name="sr0" serial="VMware_Virtual_SATA_CDRW_Drive_00000000000000000001"] io_reads value=12
> [name="sr0" serial="VMware_Virtual_SATA_CDRW_Drive_00000000000000000001"] io_writes value=0
> [name="sr0" serial="VMware_Virtual_SATA_CDRW_Drive_00000000000000000001"] io_read_bytes value=49152
> [name="sr0" serial="VMware_Virtual_SATA_CDRW_Drive_00000000000000000001"] io_write_bytes value=0
> [name="sr0" serial="VMware_Virtual_SATA_CDRW_Drive_00000000000000000001"] io_read_time value=8
> [name="sr0" serial="VMware_Virtual_SATA_CDRW_Drive_00000000000000000001"] io_write_time value=0
> [name="sr0" serial="VMware_Virtual_SATA_CDRW_Drive_00000000000000000001"] io_io_time value=8
2015/08/29 13:16:29 Error in output [influxdb]: unable to parse 'disk_total,cluster=cdh-5.4,fstype=ext4,host=foobuntu,path=/ value=19674116096i': invalid number
2015/08/29 13:16:29 Error encountered flushing outputs

**Comment by sparrc** [comment]
Thank you @vhajdari for the detailed report, it looks like you might be running a version of telegraf that is incompatible with your version of InfluxDB: https://github.com/influxdb/telegraf#installation

what is your telegraf version and influxdb version?

**Comment by vhajdari** [comment]
Hi Cameron,

I'm running InfluxDB v0.9.2

Regards,

Tony Hajdari

**Comment by vhajdari** [comment]
Hi Cameron,

Just upgraded InfluxDB to 0.9.3 and that did the trick.  I suppose RTMF
should be at the top of the support section :-)



Regards,

Tony Hajdari

**Comment by vhajdari** [comment]
Upgrading to the latest versions of InfluxDB and Telegraf resolved the issue.

**Comment by sparrc** [comment]
Thank you for closing :+1: :-)
