### ISSUE TITLE
How can I get the usage of a Plugin, ./telegraf -usage in doc does not work

### ISSUE THREAD

**Issue by serenabi** [influxdb/telegraf#196]
How can I get the usage of a Plugin, ./telegraf -usage in doc does not work

**Comment by sparrc** [comment]
./telegraf -usage <plugin_name>

ie

./telegraf -usage cpu

**Comment by mbrochh** [comment]
I tried that for many commands but usually it just returns something useless like `# Read metrics about disk usage by mount point`

Are the plugins all not documented, yet?

**Comment by sparrc** [comment]
@mbrochh correct, they are not all documented. If it only returns that then there are no config options for the plugin
