### ISSUE TITLE
Redis plugin should report the number of keys

### ISSUE THREAD

**Issue by mabushey** [influxdb/telegraf#213]
The data is available from INFO:
```
# redis-cli INFO | egrep -e "^db0"
db0:keys=895,expires=892,avg_ttl=16531936578
```

This reports just the keys:
```
# redis-cli INFO | egrep -e "^db0"|sed -e 's/^.\+:keys=//'|sed -e 's/,.\+//'
895
```
 
The number of keys and the number of clients are the most import metrics. The code looks really clean, but I have no experience in Go or I would add this. Thanks!

**Comment by sparrc** [comment]
thanks @mabushey I am not a redis expert but this is actually the second request for the same thing, so obviously it is important to redis users: https://github.com/influxdb/telegraf/issues/205

I'm going to close this case as a duplicate, but it's information will get linked into that original case, thanks so much for reporting it! :+1:
