### ISSUE TITLE
Proposal: add another metric for (used - cached - buffer)

### ISSUE THREAD

**Issue by gdm85** [influxdb/telegraf#214]
I've seen in [memory.go](https://github.com/influxdb/telegraf/blob/master/plugins/system/memory.go) how telegraf is leveraging the ``vmstat`` metrics for memory.

This however, paves the way for a newbie mistake on how these metrics are interpreted/charted (see also: http://www.linuxatemyram.com/).

Would it be a viable idea to add a new metrics that basically is just ``mem_used - mem_cached``?
I am asking this because as I am trying to render this in Grafana I've been hit by the pains of being new to both InfluxDB and Grafana :)

All feedback welcome!

**Comment by sparrc** [comment]
Good suggestion! I actually have a change to the memory plugin that will have it gathering the following metrics:
- total
- free
- used
- actual_free
- actual_used

Where actual_free and actual_used are what you are looking for. On linux it will be `mem_used - mem_cahced - mem_buffer`

**Comment by gdm85** [comment]
@sparrc if you're going to change the memory plugin in a non-backward-compatible way, I'd suggest to **not** have the confusing ``actual_`` prefix at all. I mean, why would anybody be interested in the non-actual value for a metric called ``free``/``used``? :) What the telegraf set should contain is, IMO:
* total
* free
* used

For example look at the output of ``free`` on Linux:
```
             total       used       free     shared    buffers     cached
Mem:       7827620    1527536    6300084     115992      46980     546668
-/+ buffers/cache:     933888    6893732
Swap:            0          0          0
```

We really want to have the 3rd line only:
```
-/+ buffers/cache:     933888    6893732
```
Which contains used and free memory, whose sum is the perfect total.

If you can think of an use for the cached/buffers metrics, then those should be separate but the meaning of the word "free" and "used" should be kept to the most common interpretation of such word, regardless of the technical meaning (we are not going to call it ``free-as-you-ask-for-it`` but rather just ``free``).

**Comment by sparrc** [comment]
@gdm85 I definitely see your point, and looking around I see that `Scout` reports just the "actual" metrics: http://blog.scoutapp.com/articles/2010/10/06/determining-free-memory-on-linux

I'm going to ask around and see what other people think, but I'm leaning towards your approach

**Comment by sparrc** [comment]
I'm looking at other collection tools, and actually see that they generally do NOT redefine "used" memory as the `used - cached - buffer`

I'm thinking that it might be better to keep it as-is. Re-defining `used` to be `used - cache - buffer` might be more intuitive to beginners, but I think that it would be less intuitive for users who are experienced with this concept of "free" and "used" memory in linux and other *nix systems.

**Comment by dgnorton** [comment]
I think it's best to keep it consistent with the OS and not store values in a way that are (mostly) unique to telegraf & influxdb.

**Comment by gdm85** [comment]
@sparrc I think ``free`` is reported that way on *nix systems for legacy reasons; on a new system you can choose to go with legacy/standard or stick to more intuitive meaning (and close to the word meaning).

If you want to keep it close to the OS, then an option would be (as per OP) to just add a ``net_free`` or similar that basically removes cached and buffer from used.

Or else we want **every** user to create aggregate metrics for this? :)

**Comment by sparrc** [comment]
@gdm85 how about this:

- total
- free
- used
- available

Reason being, it looks like the linux kernel is actually addressing this confusion, and as of kernel `2.6.27+` is reporting a `MemAvailable` stat in `/proc/meminfo`

**Comment by gdm85** [comment]
@sparrc thanks! great job :)
