### ISSUE TITLE
Varnishstat plugin

### ISSUE THREAD

**Issue by damstux** [influxdb/telegraf#221]
It will be great to have a varnishstat plugin to collect varnish metrics

**Comment by damstux** [comment]
the exec module and varnishstat -j do the job !

**Comment by sparrc** [comment]
perfect! can we close this then?

**Comment by sparrc** [comment]
Closing because it appears the exec plugin can be used, please re-open if otherwise

**Comment by mwpastore** [comment]
@damstux Would it be possible for you to document your configuration as an example for future googlers, like me? 😄

**Comment by sparrc** [comment]
fwiw, we've also got #1173 coming soon
