### ISSUE TITLE
InfluxDB Collector Plugin (using SHOW STATS)

### ISSUE THREAD

**Issue by skynet** [influxdb/telegraf#229]
Could Telegraf help with streamlining and visualizing InfluxDB stats in Grafana?
https://influxdb.com/blog/2015/09/22/monitoring_internal_show_stats.html

**Comment by sparrc** [comment]
@skynet I believe those stats are already in InfluxDB, so I'm not sure there is much for telegraf to do, @otoolep correct me if I'm wrong

**Comment by skynet** [comment]
True, they are, but I don't think that they are stored in a time series. Correct me if I am wrong :) Moreover, it would be nice to funnel those stats through Telegraf and use the output in a consistent fashion, similar to what we do with other Telegraf collectors.

**Comment by otoolep** [comment]
Yes, the stats are stored in the `_internal` database, as explained in the blog post.

**Comment by skynet** [comment]
I still have to see a use case with SHOW STATS plotted on a Grafana chart.

**Comment by otoolep** [comment]
I am confused. Everything from SHOW STATS is also available by SELECTing on
the internal database, as explained in the post. You feed that SELECT query
to Grafana.

What more do you need? Am I missing your point?

**Comment by skynet** [comment]
No, that's fine, it's just that I have to put this in Grafana myself and see how it works. It is, indeed, very important to be able to monitor InfluxDB along with the other services running on a particular (Linux) machine.

**Comment by sparrc** [comment]
@skynet Are you talking about using Telegraf for outputting that data from InfluxDB into other outputs like Kafka? How does Telegraf help you to put the data into Grafana? Isn't it just an Influx query either way?

**Comment by jcmartins** [comment]
@skynet you don't need use telegraf, because the stats are store in Influxdb, so you can read it by Grafana.

**Comment by skynet** [comment]
Yes I agree with both of you, can simply plugin the InfluxDB stats data directly into Grafana. But I can't just agree with declining any use for Telegraf here if you look at Telegraf from the perspective of being the middleware, having the role of providing a unified model of aggregating data, standardizing it, and subsequently making it possible and seamless to build the visuals (e.g. using Grafana).

**Comment by otoolep** [comment]
That is valid, and we do have plans to add an InfluxDB monitoring plugin -- or PRs are very welcome -- for InfluxDB.

**Comment by skynet** [comment]
Wonderful, thank you.
