### ISSUE TITLE
Bcache plugin

### ISSUE THREAD

**Issue by cornerot** [influxdb/telegraf#233]
Bcache statistics

**Comment by sparrc** [comment]
@cornerot thanks for the suggestion, any other details you could provide would be much appreciated!

**Comment by cornerot** [comment]
#cache sets

/sys/fs/bcache/\<cset-uuid\>
* cset-uuid - UUIDs of cache sets

```sh
shell:  ls -d /sys/fs/bcache/*-*-*-*-*
output: /sys/fs/bcache/663955a3-765a-4737-a9fd-8250a7a78411
```

## metrics

**stats**

path
 * /sys/fs/bcache/3e35941c-088d-4c34-971c-492886250738/stats_total

files
* bypassed
* cache_bypass_hits
* cache_bypass_misses
* cache_hit_ratio
* cache_hits
* cache_miss_collisions
* cache_misses
* cache_readaheads

description
* bypassed
    * Amount of IO (both reads and writes) that has bypassed the cache
    It contains pretty-printed values: 1036, 520.0k, 456.0M, 300.0G (k, M, G, T, P, E, Z, Y)

    ```sh
    shell:  cat bypassed
    output: 3.4T
    ```

* cache_bypass_misses
    * Hits and misses for IO that is intended to skip the cache are still counted,
    but broken out here.
    
    ```sh
    shell:  cat cache_bypass_hits
    output: 8450417
    ```

* cache_hit_ratio
    * Hits and misses are counted per individual IO as bcache sees them; a
    partial hit is counted as a miss (possible values 0 - 100) 
    
    ```sh
    shell:  cat cache_hit_ratio
    output: 50
    ```

* cache_hits
    ```sh
    shell:  cat cache_hits
    output: 473978810
    ```

* cache_miss_collisions
    * Counts instances where data was going to be inserted into the cache from a
    cache miss, but raced with a write and data was already present (usually 0
    since the synchronization for cache misses was rewritten)
    
    ```sh
    shell:  cat cache_miss_collisions
    output: 154237
    ```
    
* cache_misses
    ```sh
    shell:  cat cache_misses
    output: 49838850
    ```
    
* cache_readaheads
    * Count of times readahead occurred.
    
    ```sh
    shell:  cat cache_readaheads
    output: 0
    ```


# backing devices

/sys/fs/bcache/\<UUID\>/bdev\<0..n\>
* bdev\<0..n\> - Symlink to each of the attached backing devices.

```sh
shell:  ls -d /sys/fs/bcache/663955a3-765a-4737-a9fd-8250a7a78411/bdev+([[:digit:]])
output: /sys/fs/bcache/663955a3-765a-4737-a9fd-8250a7a78411/bdev0
```

```sh
shell:  readlink /sys/fs/bcache/663955a3-765a-4737-a9fd-8250a7a78411/bdev0
output: ../../../devices/virtual/block/md10/bcache
```

where md10 - system device name

## metrics

**dirty_data**

path
* /sys/fs/bcache/663955a3-765a-4737-a9fd-8250a7a78411/bdev0

files
* dirty_data

description
* dirty_data
    * Amount of dirty data for this backing device in the cache.
    It contains pretty-printed values: 1036, 520.0k, 456.0M, 20.0G (k, M, G)

    ```sh
    shell:  cat dirty_data
    output: 11.0M
    ```

**stats**

path
* /sys/fs/bcache/663955a3-765a-4737-a9fd-8250a7a78411/bdev0/stats_total

files
* bypassed
* cache_bypass_hits
* cache_bypass_misses
* cache_hit_ratio
* cache_hits
* cache_miss_collisions
* cache_misses
* cache_readaheads

description
* same as for cache set

**Comment by cornerot** [comment]
plugin is almost ready

**Comment by cornerot** [comment]
https://github.com/influxdb/telegraf/pull/286
