### ISSUE TITLE
Error during installation (not found) - Package deb

### ISSUE THREAD

**Issue by JulienChampseix** [influxdb/telegraf#236]
Hi,

Find bellow an error during the instalation of the deb:

root@# dpkg -i telegraf_0.1.9_amd64.deb
Selecting previously unselected package telegraf.
(Reading database ... 57300 files and directories currently installed.)
Preparing to unpack telegraf_0.1.9_amd64.deb ...
Unpacking telegraf (0.1.9) ...
Setting up telegraf (0.1.9) ...
/var/lib/dpkg/info/telegraf.postinst: 9: /var/lib/dpkg/info/telegraf.postinst: [[: not found
 Removing any system startup links for /etc/init.d/telegraf ...
 Adding system startup for /etc/init.d/telegraf ...
   /etc/rc0.d/K20telegraf -> ../init.d/telegraf
   /etc/rc1.d/K20telegraf -> ../init.d/telegraf
   /etc/rc6.d/K20telegraf -> ../init.d/telegraf
   /etc/rc2.d/S20telegraf -> ../init.d/telegraf
   /etc/rc3.d/S20telegraf -> ../init.d/telegraf
   /etc/rc4.d/S20telegraf -> ../init.d/telegraf
   /etc/rc5.d/S20telegraf -> ../init.d/telegraf

distro:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by sparrc** [comment]
This was fixed by #232, I can re-roll a `0.1.9.1` with that fix if it affected your installation. Did you end up with telegraf 0.1.9 on your system anyways?

**Comment by sparrc** [comment]
closing as fixed by #232, it will be in the next release
