### ISSUE TITLE
How do I select from InfluxDB what hosts are in the DB?

### ISSUE THREAD

**Issue by mabushey** [influxdb/telegraf#238]
I would like to select the hosts for a Grafana templated query, but I don't know how. It seems like something this simple should be documented, but I can't find it. Trying to use a "SQL Like" query language is about as productive as trying to eat "Food Like" plastic.

**Comment by gotyaoi** [comment]
Something like `SHOW TAG VALUES WITH KEY=host` I think.
https://influxdb.com/docs/v0.9/query_language/schema_exploration.html

**Comment by mabushey** [comment]
Awesome! That worked. :) Thank you @gotyaoi
