### ISSUE TITLE
Exec documentation, provide JSON examples

### ISSUE THREAD

**Issue by dbellantuono** [influxdb/telegraf#245]
Hi guys!
I tried to write a script to send metrics via exec plugin, but i didn't fund the correct JSON output format.
Can you add in documentation an example with JSON output?

**Comment by sparrc** [comment]
@jpalay @alvaromorales Could one of you guys take care of this? And don't forget to sign up for Hacktoberfest https://hacktoberfest.digitalocean.com/ ;-)
