### ISSUE TITLE
Negative values are reported by mongodb plugin

### ISSUE THREAD

**Issue by testuser7** [influxdb/telegraf#253]
Negative values are reported (*_per_sec and *_net_* counters) when mongodb instance freezes for some time.

`time host hostname state value`
`2015-10-09T09:22:19Z  "mongodb" "127.0.0.1:27019" "PRI" 420`
`2015-10-09T09:22:30Z  "mongodb" "127.0.0.1:27019" "PRI" 438`
`2015-10-09T09:28:41Z  "mongodb" "127.0.0.1:27019"  -73293`
`2015-10-09T09:28:52Z  "mongodb" "127.0.0.1:27019"  192`
`2015-10-09T09:29:04Z  "mongodb" "127.0.0.1:27019"  231`
`2015-10-09T09:29:16Z  "mongodb" "127.0.0.1:27019"  245`
`2015-10-09T09:29:27Z  "mongodb" "127.0.0.1:27019"  246`
`2015-10-09T09:29:39Z  "mongodb" "127.0.0.1:27019"  249`
`2015-10-09T09:29:51Z  "mongodb" "127.0.0.1:27019"  243`
`2015-10-09T09:30:02Z  "mongodb" "127.0.0.1:27019"  248`
`2015-10-09T09:30:14Z  "mongodb" "127.0.0.1:27019"  250`
`2015-10-09T09:30:26Z  "mongodb" "127.0.0.1:27019"  262`
`2015-10-09T09:30:37Z  "mongodb" "127.0.0.1:27019"  346`
`2015-10-09T09:30:49Z  "mongodb" "127.0.0.1:27019"  396`
`2015-10-09T09:31:01Z  "mongodb" "127.0.0.1:27019"  459`
`2015-10-09T09:31:12Z  "mongodb" "127.0.0.1:27019" "SEC" 501`
`2015-10-09T09:31:24Z  "mongodb" "127.0.0.1:27019" "SEC" 224`

**Comment by sparrc** [comment]
@testuser7 what is this output from? Can you provide telegraf debug output and version number?

**Comment by testuser7** [comment]
This is result of query `select * from mongodb_commands_per_sec where "hostname" = '127.0.0.1:27019'`

I don't have debug logs. Telegraf 0.1.9 was used.
