### ISSUE TITLE
Issue on kafka_consumer plugin

### ISSUE THREAD

**Issue by pugna0** [influxdb/telegraf#257]
Hi bro,
I clone this project from master on Ubuntu14.04.
I just put kafka plugin in the config file, and output it to influxdb.
It works well but the result is consits of "kafka_" and the data in the topic , like:
cpu_time_guest  (source data )
kafka_cpu_time_guest (generated by telegraf)

and I write "aaa" into kafka , then using telegraf with that topic, this log information clearly indicate that telegraf is analyzing "aaa".
2015/10/12 17:54:53 Error in plugin [kafka] : unable to parse 'aaa': missing fields
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Another problem is that telegraf just gather once in kafka, log informations as follows: 
2015/10/12 17:08:41 Cranking default (10s) interval, gathered 2900 metrics from 1 plugins in 1.302290095s
2015/10/12 17:08:50 Cranking default (10s) interval, gathered 0 metrics from 1 plugins in 1.075610727s
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The final result I want is the status of kafka_consumer as "redis plugin" .

**Comment by sparrc** [comment]
how would you expect telegraf to parse "aaa"? I believe that the kafka consumer plugin needs to be in the line-protocol format

**Comment by sparrc** [comment]
it's also expected that telegraf plugins prepend measurements with the plugin name

**Comment by pugna0** [comment]
I mean, the contents kafka-plugin gathered are not run-time status or performance of consumer on a topic , they are just source data. The function of kafka plugin is not like redis 's.

**Comment by sparrc** [comment]
that is why it's called a `kafka_consumer`, it consumes kafka data. I suppose a statistics-gathering plugin would just be called `kafka`

This should be spelled out in a README, see #177

**Comment by pugna0** [comment]
Did I make a mistake? These two do not have same function?
# read metrics from a Kafka topic
[kafka]
# Read metrics from one or many redis servers
[redis]

**Comment by pugna0** [comment]
I copy them from config-sample.

**Comment by sparrc** [comment]
@pugna0, correct, they don't have the same function. You can submit a PR if you would like to change the wording, and as I said you can also help the project by submitting a README.

**Comment by pugna0** [comment]
I've got it , thank you very much , I'll leave messages for you if I have any ideas.
