### ISSUE TITLE
Running raw `telegraf` command without a config file causes error

### ISSUE THREAD

**Issue by mjdesa** [influxdb/telegraf#26]
Simply running `telegraf` by itself yields this error

```
2015/06/23 13:51:16 Error in plugins: Post write?consistency=&db=&precision=&rp=: unsupported protocol scheme ""
```

If you generate a sample config and run it with the config file, everything works fine.

![screen shot 2015-06-23 at 1 54 15 pm](https://cloud.githubusercontent.com/assets/1477539/8317011/67f702ee-19af-11e5-8c42-e5673d7af23e.png)

**Comment by benfb** [comment]
Could we load in the sample config by default?

**Comment by zepouet** [comment]
@benfb else to stop the processus if no configuration is given.

**Comment by sparrc** [comment]
I would say the solution should be to fail and exit with a better error message if no config file is specified, marking as a bug
