### ISSUE TITLE
Skip virtual interface

### ISSUE THREAD

**Issue by farss** [influxdb/telegraf#263]
I don't want to gather interface data of virtual interface. How skip virtual interface.

**Comment by sparrc** [comment]
what plugin are you talking about? Have you tried plugin `drop` or `tagdrop` parameters? https://github.com/influxdb/telegraf#plugin-options

**Comment by ekini** [comment]
Or if you're talking about net plugin, then
```
 # By default, telegraf gathers stats from any up interface (excluding loopback)
 # Setting interfaces will tell it to gather these explicit interfaces,
 # regardless of status.
 #
 # interfaces = ["eth0", ... ]
```
