### ISSUE TITLE
panic in accumulator if nil is passed as the third parameter to Add

### ISSUE THREAD

**Issue by gotyaoi** [influxdb/telegraf#289]
I was testing the changes I had made for the config directory support when I came across this. The changes here: https://github.com/influxdb/telegraf/commit/6977119f1e208bbaae7584168af3a0226ceb065a#diff-2df0b9f3bc0da3ee13966a69e386ff84R145 will panic if Add is passed nil as the tags parameter. A quick grep shows this only happens in the system plugin, the puppetagent plugin and as an example in the CONTRIBUTING.md file.

Edit: my grep was insufficient. This also occurs in the memory plugin, as it passes `map[string]string(nil)`.

**Comment by sparrc** [comment]
I'm working on overhauling the accumulator and already have a fix for this in that branch

**Comment by gotyaoi** [comment]
Ok, cool.

**Comment by sparrc** [comment]
I'll leave this case open until I actually get that pushed, thanks for the report @gotyaoi!
