### ISSUE TITLE
Hostname is not passed as a tag

### ISSUE THREAD

**Issue by alvaromorales** [influxdb/telegraf#29]
I installed telegraf using the Debian/Ubuntu package on the README file. It is sending metrics to influxdb 0.9. The hostname of the machine running telegraf is not being passed as a tag with metrics.

**Comment by jimconner** [comment]
+1 for this issue - I'm seeing the same problem too. Additionally uncommenting the ```tags={ "dc" : "us-east-1" }``` line in the sample config causes a parse error.

**Comment by toddboom** [comment]
I think this might be the same as #18 - we should have this fixed in the next day or so and will cut a release as soon as it's done.

**Comment by jcmartins** [comment]
please use full hostname ( hostname -f ) in Amazon AWS it's important because the instance-id  in a lof of case only show using hostname -f

**Comment by jimconner** [comment]
I've just tested with the current master branch after https://github.com/influxdb/influxdb/issues/3131 got merged, and can confirm that this has fixed the issue with tags not being passed. Is there any estimate for when the next release (incorporating this fix) is due to land? Thanks.

**Comment by pauldix** [comment]
@jimconner we'll cut a release later today

**Comment by toddboom** [comment]
This should be fixed in v0.1.2, which is now available.

**Comment by alvaromorales** [comment]
I'm running telegraf-0.1.2 (with influxdb 0.9.1-rc1) and can confirm that the issue is fixed. Thanks!

**Comment by rdxmb** [comment]
As described here
https://community.influxdata.com/t/why-is-hostname-not-replaced-with-its-content-when-using-in-global-tags/2603
the same problem again occurs with telegraf v1.4.1.
Can we reopen this issue or should I create a new one?
