### ISSUE TITLE
flushinterval causes delay for latest data

### ISSUE THREAD

**Issue by gotyaoi** [influxdb/telegraf#294]
Just doing some testing with the new accumulator, and ran into an odd little issue. The way it seems to be operating, for collections, it runs immediately after startup, then waits `Interval`, then collects again, but for flushing, it waits `FlushInterval` after startup, then flushes. This has the effect that looks like this in the log:
```
2015/10/20 14:03:54 Default (10s) interval, gathered metrics from 8 plugins in 33.859066ms
2015/10/20 14:04:04 Flushed 146 metrics in 28.896469ms
2015/10/20 14:04:04 Default (10s) interval, gathered metrics from 8 plugins in 37.42883ms
2015/10/20 14:04:14 Flushed 311 metrics in 18.049086ms
2015/10/20 14:04:14 Default (10s) interval, gathered metrics from 8 plugins in 43.533597ms
2015/10/20 14:04:24 Flushed 21 metrics in 22.573901ms
```
With the flush occurring immediately before the gather. The result of this is a lack of the latest data point in the outputs. It gets inserted at the next flush, of course, but at that time it is `FlushInterval` out of date. This is fine, I think, for cases where `Interval != FlushInterval`, but in the case where they are equal, is there any way to get the flush to occur after the gather?

**Comment by sparrc** [comment]
hmm this is a bit tough to guarantee since they are two independent threads. 99.9% correct solution could be to sleep for a few milliseconds when the flusher thread starts up

**Comment by sparrc** [comment]
Thanks for the report @gotyaoi! I've pushed a change to delay the startup of the flusher

**Comment by gotyaoi** [comment]
Looks good.
