### ISSUE TITLE
MySQL plugin takes wrong server tag if the password contains '@'

### ISSUE THREAD

**Issue by adithyabenny** [influxdb/telegraf#297]
https://github.com/influxdb/telegraf/blob/master/plugins/mysql/mysql.go#L135 is how the MySQL plugin takes the server tag. It should take the last element of the array, as opposed to the second element, otherwise it'll output the wrong result if the password contains the character '@'.

**Comment by sparrc** [comment]
thanks for the report

**Comment by adithyabenny** [comment]
The sever tag should be 'localhost' even if the `serv` variable is "root:root@http://10.0.0.18/?tls=false" or "root:passwd@tcp(127.0.0.1:3036)/?allowOldPasswords=1"

**Comment by adithyabenny** [comment]
@sparrc the updated plugin returns 'localhost:3306' as the server tag. Isn't that undesirable? Shouldn't the server tag consist of just 'localhost'?

**Comment by sparrc** [comment]
I'd prefer it have port and server, since that is the full address
