### ISSUE TITLE
Normalize telegraf collection interval on even intervals

### ISSUE THREAD

**Issue by sparrc** [influxdb/telegraf#301]
ie, if you specify `interval = "10s"` then you will get metrics stamped at `:00`, `:10`, `:20`, etc.

This will also introduce a `flush_jitter` option so that multiple telegraf instances don't all flush at exactly the same time.

**Comment by sparrc** [comment]
@daviesalex I wanted to let you know that this is also in HEAD because you mentioned this in case #285. I'm hoping that the jitter is enough to allay your concerns, the default behavior is a jitter of 5s with a flush interval of 10s.

The way that it's implemented, `flush_interval` is the minimum flush time, and `flush_interval + flush_jitter` would be the max flush time.

It sounds like you are experienced running Telegraf instances at scale, so I'd like to get your input on this before it ends up in the next release.

**Comment by daviesalex** [comment]
Some initial real world data from this can be found at https://github.com/influxdb/telegraf/pull/298#issuecomment-150614275
