### ISSUE TITLE
[tags] from config file are not getting picked up

### ISSUE THREAD

**Issue by sparrc** [influxdb/telegraf#302]
AFAIK, this is only on HEAD

**Comment by sparrc** [comment]
@gotyaoi this looks to be related to your config changes, can you take a look at this?

Using the tags dict in the config file is not getting applied, like the config below

```
[tags]
  user = "sparrc"
```

**Comment by gotyaoi** [comment]
Ah, I see what's wrong. I think I was in the middle of a change there and forgot to finish it. I'll submit a fix later today.

**Comment by sparrc** [comment]
thank you :+1:
