### ISSUE TITLE
Error Message on .deb-Install on Ubuntu 14.04

### ISSUE THREAD

**Issue by nohn** [influxdb/telegraf#305]
sudo dpkg -i telegraf_0.1.9_amd64.deb 
    Selecting previously unselected package telegraf.
    (Reading database ... 106864 files and directories currently installed.)
    Preparing to unpack telegraf_0.1.9_amd64.deb ...
    Unpacking telegraf (0.1.9) ...
    Setting up telegraf (0.1.9) ...
    /var/lib/dpkg/info/telegraf.postinst: 9: /var/lib/dpkg/info/telegraf.postinst: [[: not found
     Removing any system startup links for /etc/init.d/telegraf ...
     Adding system startup for /etc/init.d/telegraf ...
       /etc/rc0.d/K20telegraf -> ../init.d/telegraf
       /etc/rc1.d/K20telegraf -> ../init.d/telegraf
       /etc/rc6.d/K20telegraf -> ../init.d/telegraf
       /etc/rc2.d/S20telegraf -> ../init.d/telegraf
       /etc/rc3.d/S20telegraf -> ../init.d/telegraf
       /etc/rc4.d/S20telegraf -> ../init.d/telegraf
       /etc/rc5.d/S20telegraf -> ../init.d/telegraf

**Comment by ekini** [comment]
It should have been fixed in #236

**Comment by sparrc** [comment]
Yep, this is fixed and available in version 0.2.0, thanks for the report @nohn
