### ISSUE TITLE
NSQ output

### ISSUE THREAD

**Issue by sparrc** [influxdb/telegraf#309]
We should write an NSQ output sink, looks fairly straightforward since it's a Go project and they have an officially supported Go client.

Official Go client:
https://github.com/nsqio/go-nsq

Example writer:
https://github.com/nsqio/nsq/blob/master/apps/to_nsq/to_nsq.go

**Comment by samahee** [comment]
+1

**Comment by jrxFive** [comment]
Should the output sink have the option to do a lookup for the "topic" against nsqlookupd or just directly to a set of nsqd instances?

**Comment by sparrc** [comment]
@jrxFive Doing discovery would be a good idea. What exactly do you mean about the measurement times? Convering them to a different unit?

Personally I would prefer to just use what they give us to avoid confusion. It's easy enough in influx to divide by whatever scale you need.

**Comment by jrxFive** [comment]
@sparrc, I was asking if there should be an adjustments to the default config given. The time duration for those defaults are in nanoseconds was just trying to give the base unit :). But yea I agree ill stick to the defaults and incorporate a lookupd option.

**Comment by sparrc** [comment]
closed by #325
