### ISSUE TITLE
nothing prevents launching multiple instances of telegraf

### ISSUE THREAD

**Issue by beckettsean** [influxdb/telegraf#31]
Not sure if that's intentional or not, but it could lead to confusion. I can see a use case, where I want to sample different metrics at different intervals.

What's the intention?

**Comment by sparrc** [comment]
Sounds like a bug, will look into it

**Comment by sparrc** [comment]
I'm going to close this because Telegraf doesn't bind to any ports, and therefore there is no real reason to disallow this. As the plugins expand, we might integrate a UDP statsd-style listener, in which case we would have to prevent another from starting up based on the bind port.
