### ISSUE TITLE
ZFS plugin

### ISSUE THREAD

**Issue by cornerot** [influxdb/telegraf#317]
ZFS metrics

**Comment by mabushey** [comment]
I triple second this!

**Comment by cornerot** [comment]
plugin is almost ready

**Comment by schors** [comment]
Hm... but on what OS? Not FreeBSD...

**Comment by cornerot** [comment]
No :) http://zfsonlinux.org/

**Comment by schors** [comment]
Well, this time hell knows what

**Comment by cornerot** [comment]
Yes, I know
