### ISSUE TITLE
disk plugin reports bind mounts as duplicates

### ISSUE THREAD

**Issue by azrdev** [influxdb/telegraf#319]
Consider an `/etc/fstab` like
```
Label=foo  /mnt        auto  default 0 0
/mnt/sub   /media/sub  none  bind    0 0
...
```
i.e. a mount point `/mnt` and some subdirectories of it bind-mounted to some other directory.

Such configuration leads to the disk plugin of telegraf reporting disk usage statistics for each of these bind mounts separately, with the same data (that of the original mount point).

**Comment by sparrc** [comment]
Closing this as expected behavior.

What would you want it to do? Ignore your bind mounts? If they're in fstab seems like they should be listed. You can ignore them using `tagpass/tagdrop` or `pass/drop` filters. https://github.com/influxdb/telegraf#plugin-options
