### ISSUE TITLE
Config ignores toml struct tags

### ISSUE THREAD

**Issue by ekini** [influxdb/telegraf#320]
If we have a config struct in a plugin like
```go

struct Config {
 Groups []*Group `toml:"group"`
}
```
Then telegram will fail at the start with `could not find field in pluginname.Config matching group`.

Most likely, it's caused by #295

**Comment by ekini** [comment]
@gotyaoi any ideas?

**Comment by sparrc** [comment]
thanks for the report, @gotyaoi could you please take a look at this as soon as possible?

**Comment by sparrc** [comment]
@ekini are there any plugins that currently rely on this behavior?

**Comment by gotyaoi** [comment]
I'll take a look.

**Comment by ekini** [comment]
@sparrc although there are some plugins that use struct tags, all of them luckily work correctly,
except my unreleased plugin :)
```bash
[ekini@c7 telegraf]$ grep -R toml plugins/ outputs/
plugins/mongodb/mongodb.go:	CaCerts []string `toml:"cacerts"`
plugins/ping/ping.go:	PingInterval float64 `toml:"ping_interval"`
plugins/ping/ping.go:	// Build the ping command args based on toml config
plugins/system/cpu.go:	PerCPU   bool `toml:"percpu"`
plugins/system/cpu.go:	TotalCPU bool `toml:"totalcpu"`
plugins/procstat/procstat.go:	PidFile string `toml:"pid_file"`
outputs/influxdb/influxdb.go:	URLs      []string `toml:"urls"`
outputs/kafka/kafka.go:	RoutingTag string `toml:"routing_tag"`
outputs/amqp/amqp.go:	RoutingTag string `toml:"routing_tag"`
outputs/mqtt/mqtt.go:	Servers     []string `toml:"servers"
```

**Comment by gotyaoi** [comment]
Ok, so those work correctly because they are, shall I say, close enough. The merging code currently strips underscores and lowercases to match between a key in toml and a field in the struct. The struct tag is not currently consulted. I'll put in matching on the struct tag.

**Comment by gotyaoi** [comment]
@ekini Could you please give the patch from https://github.com/gotyaoi/telegraf/commit/d85cf9b9aefb072b8dba3467a01d59a01d490c18 a try? If that works for you, I'll rebase and submit a PR.

**Comment by ekini** [comment]
@gotyaoi it works, but it matches both "group" and "groups". I'd use something like ekini@600c48abf96506a8a5a6ed125d8648b0369e3df3

Also, I think it's better not to fail when config dir doesn't exist, because .rpm and .deb post-install scripts don't create it, but it's specified in startup script. Please, check ekini@5b96193b755a27b084aabc4ac3f62471ad6104d2

**Comment by gotyaoi** [comment]
Ah, yes, that definitely makes sense. @sparrc that could probably be taken as is, or I could squash it down into one commit on my branch, whichever you would like.

Regarding the config directory, I think that if it's been specified at the command line, it should be an error if it doesn't exist. In that case, it should probably be created by the packages. I'll put together a commit for that a bit later.

**Comment by sparrc** [comment]
@ekini I think that it's okay for it to error if the directory does not exist. The .deb and .rpm packages should create the directory if it's specified in the startup script.

**Comment by sparrc** [comment]
@gotyaoi if you could squash and submit a PR, that would be easiest for me, thanks!
