### ISSUE TITLE
CPU Usage Plugin

### ISSUE THREAD

**Issue by tylernisonoff** [influxdb/telegraf#33]
I want to add support for CPU Usage (percentage).  I've generally seen this done by querying /proc/stat, sleeping for a second, querying again, and calculating the percentage from the diff.  Does this sound reasonable if added to the current cpu plugin?

**Comment by dennisjac** [comment]
Can plugins have state? If so you could store the values and time between runs and then on the next run subtract the values from the previous run and divide by the elapsed time between the runs (which should be the interval). That way you don't have to wait a second to get an actual value and you would get an average percentage over the whole interval which is probably what most people rather want anyway.

**Comment by steverweber** [comment]
I did what @dennisjac said.  needed to store the previous state and calc the deltas.

Here is one i did for heka, its in `lua` not `go` but perhaps some of the logic is still helpful.
https://github.com/mozilla-services/heka/blob/dev/sandbox/lua/filters/procstat.lua

**Comment by sparrc** [comment]
Sounds like a good idea, should probably be integrated into the existing system plugin

**Comment by sparrc** [comment]
this has been implemented, thanks @jpalay!

**Comment by deanefrati** [comment]
Hi, sorry but i may be missing something... i don't see any percentage measurements is there anything special that needs to be done in order to turn these on?

**Comment by sparrc** [comment]
@deanefrati please open a new issue if you are having problems with CPU usage reporting. Please also include Telegraf version, command you are running, and output.

thanks!
