### ISSUE TITLE
Problem with exec (test says OK, but service errors)

### ISSUE THREAD

**Issue by mabushey** [influxdb/telegraf#330]
```
root@www:~#  /opt/telegraf/telegraf -config /etc/opt/telegraf/telegraf.conf -test -filter exec                                                                                                                         
map[kafka:0x5261e0 opentsdb:0x528420 amqp:0x521c50 datadog:0x523ec0 influxdb:0x5256e0]
OUTPUT ENABLED:  influxdb
* Plugin: exec Collection 1
> [] exec__sf_queue value=0
* Plugin: exec Collection 2
> [] exec__sf_queue value=0
```

looks OK from the test....

```
# systemctl status telegraf 
...
Oct 29 00:28:14 www telegraf[10125]: 2015/10/29 00:28:14 Tags enabled: host=www
Oct 29 00:28:14 www telegraf[10125]: 2015/10/29 00:28:14 Error in plugin [exec]: exec: unable to parse output of '/etc/opt/telegraf/sf_pull.sh' as JSON, unexpected end of JSON input
```
```
# /etc/opt/telegraf/sf_pull.sh
{ "sf_queue": 0 }
```

Looks like json, the telegraf test thinks it's valid, but the telegraf service disagrees...

```
/etc/opt/telegraf/telegraf.conf
...
[[exec.commands]]
  command = "/etc/opt/telegraf/sf_pull.sh"
```

**Comment by sparrc** [comment]
@mabushey I haven't been able to reproduce on 0.2.0, what version are you running?

`/opt/telegraf/telegraf -version`

**Comment by mabushey** [comment]
I was running 1.9, I upgraded to 2.0. Thanks for the new version. :)

I made a more simplified version of sf_pull.sh:
```
# cat /etc/opt/telegraf/sf_pull.sh
#!/bin/bash
echo "Data 0" | awk '{ print "{ \"sf_queue\": " $2 " }" }'
```

It works. This was an environmental error, it doesn't work if I run the original sf_pull.sh script as the telegraf user. It's funky that the test option apparently runs under the user executing it while the daemon runs under the telegraf user.

**Comment by sparrc** [comment]
I suppose I expect that, I'm not sure how we could execute under a user other than the current user. I know that we are making some pretty big changes to the deb and rpm packages soon for influxdb and telegraf, which might include something about users and privilege changes, @rossmcdonald can you comment?

**Comment by mabushey** [comment]
Maybe add the the documentation to test it with sudo -u telegraf  ??

**Comment by sparrc** [comment]
@mabushey I'll do that
