### ISSUE TITLE
Support sending metrics to Riemann

### ISSUE THREAD

**Issue by ipstatic** [influxdb/telegraf#34]
Are you planning on supporting different "output" methods like writing metrics to Riemann?

**Comment by pauldix** [comment]
Different output methods is definitely on the list. Riemann and Kafka come to mind

**Comment by jbfarez** [comment]
Yeah it could be a great feature ! :+1:

**Comment by panda87** [comment]
+1

**Comment by Kenuat** [comment]
I would definetely vote for heka as well

**Comment by allenj** [comment]
I've written an output for this. I'm waiting on amir/raidman#11 to be merged but the branch mentioned in the commit above works.

**Comment by babilen** [comment]
Really looking forward to this.
