### ISSUE TITLE
Part measurement to types and sub types

### ISSUE THREAD

**Issue by panda87** [influxdb/telegraf#347]
I think the measurement tag should represent a group types, for example, cpu.
Today the cpu measurement looks like this: cpu_usage_steal, and I think the measurement should be only `cpu` and `usage`, `steal` should be the types and sub type.

With this approach this will be easy for example to build more aggregate queries in Grafana and use as many WHERE and GROUP BY we can to get the right results.

**Comment by sparrc** [comment]
Thanks for the suggestion, there's already an issue for this though #152
