### ISSUE TITLE
InfluxDB log messages: CREATE DATABASE telegraf 

### ISSUE THREAD

**Issue by ChamaraG** [influxdb/telegraf#351]
I have Telegraf 0.2.0 sending data to a InfluxDB 0.9.4.2 server and in the server logs I see the following log message every few seconds. This message is generated by a Telegraf query. 

    {"log":"[http] 2015/11/06 07:14:02 172.28.213.9 - root [06/Nov/2015:07:14:02 -0800] POST /write?consistency=\u0026db=telegraf\u0026precision=s\u0026q=CREATE+DATABASE+telegraf\u0026rp= HTTP/1.1 204 0 - InfluxDBClient 0360ab76-8499-11e5-a086-000000000000 17.657307ms\n","stream":"stderr","time":"2015-11-06T15:14:02.637574183Z"}

Seems like Telegraf is periodically trying to ascertain whether the database telegraf exists in InfluxDB? Is this behaviour normal? 

Thank you.

**Comment by otoolep** [comment]
That is not right. Whatever is sending `CREATE DATABASE` is sending it to the wrong endpoint.

**Comment by ChamaraG** [comment]
Hi, thanks for the reply. I think it is Telegraf that is causing `CREATE DATABASE` as when I stop Telegraf, this message stops appearing in the InfluxDB logs and all I see is queries from my consumers. 

Is there anything I can do to trace this? I am running Telegraf with `Debug:true`, but I don't see anything unusual in the Telegraf log file.

**Comment by sparrc** [comment]
@ChamaraG Sounds like a bug, Telegraf should only run that at startup, I'll look into it

**Comment by alexarwine** [comment]
I'm hitting a similar issue; influxdb crashed last night (single node, 0.9.3), all telegraf clients (0.2.0 as well as master branch) seem to be hitting the connect timeout value; but collectd seems to be collecting fine.

increasing the timeout does not seem to help.

2015/11/06 10:00:00 Gathered metrics, (10s interval), from 9 plugins in 11.797297ms
2015/11/06 10:00:00 ERROR: Post http://10.90.13.17:8086/write?consistency=&db=telegraf&precision=s&q=CREATE+DATABASE+telegraf&rp=: net/http: request canceled (
Client.Timeout exceeded while awaiting headers)
2015/11/06 10:00:00 Error in output [influxdb]: Could not write to any InfluxDB server in cluster, retrying in 10s

corresponding influx logs:
[http] 2015/11/06 10:37:35 10.90.17.92 - telegraf [06/Nov/2015:10:37:30 -0800] POST /write?consistency=&db=telegraf&precision=s&q=CREATE+DATABASE+telegraf&rp= HTTP/1.1 500 32 - telegraf 6f9f7746-84b5-11e5-8704-000000000000 5.017700009s


Influx just crashed again so my situation may be a little different...

**Comment by sparrc** [comment]
@alexarwine that is an unrelated issue, and also I'm not sure it's an issue. If InfluxDB is down, then Telegraf won't be able to write to it, what behavior would you be expecting?

**Comment by alexarwine** [comment]
I apologize, I discovered that influx was not accepting writes by way of telegraf

**Comment by sparrc** [comment]
this is in fact a bug in the InfluxDB client, see PR above

**Comment by sparrc** [comment]
@alexarwine no problem, just making sure it wasn't a telegraf issue

**Comment by ChamaraG** [comment]
@sparrc , thank you.
