### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by syepes** [influxdb/telegraf#355]
It would be great if we could add support for FreeBSD

**Comment by sparrc** [comment]
@syepes Do you mean for pre-compiled binaries or a package you could install? Telegraf should compile on FreeBSD, afaik

**Comment by syepes** [comment]
I was thinking more that the system/net and zfs plugins be able to collect there info from fBSD.

**Comment by sparrc** [comment]
Could you be more specific about what errors you are seeing in those plugins?

**Comment by cornerot** [comment]
Currently, ZFS plugin does not work on fBSD

**Comment by syepes** [comment]
FreeBSD Build log failure:

```
# gmake
go get github.com/tools/godep
/opt/go/bin/godep go build -o telegraf -ldflags \
        "-X main.Version=v0.2.0-52-g68ef07b" \
        ./cmd/telegraf/telegraf.go
# github.com/cloudfoundry/gosigar
Godeps/_workspace/src/github.com/cloudfoundry/gosigar/concrete_sigar.go:20: cpuUsage.Get undefined (type Cpu has no field or method Get)
Godeps/_workspace/src/github.com/cloudfoundry/gosigar/concrete_sigar.go:30: cpuUsage.Get undefined (type Cpu has no field or method Get)
Godeps/_workspace/src/github.com/cloudfoundry/gosigar/concrete_sigar.go:49: l.Get undefined (type LoadAverage has no field or method Get)
Godeps/_workspace/src/github.com/cloudfoundry/gosigar/concrete_sigar.go:55: m.Get undefined (type Mem has no field or method Get)
Godeps/_workspace/src/github.com/cloudfoundry/gosigar/concrete_sigar.go:61: s.Get undefined (type Swap has no field or method Get)
Godeps/_workspace/src/github.com/cloudfoundry/gosigar/sigar_unix.go:23: cannot use stat.Ffree (type int64) as type uint64 in assignment
# github.com/fsouza/go-dockerclient/external/github.com/Sirupsen/logrus
Godeps/_workspace/src/github.com/fsouza/go-dockerclient/external/github.com/Sirupsen/logrus/terminal_freebsd.go:10: ioctlReadTermios redeclared in this block
        previous declaration at Godeps/_workspace/src/github.com/fsouza/go-dockerclient/external/github.com/Sirupsen/logrus/terminal_bsd.go:7
Godeps/_workspace/src/github.com/fsouza/go-dockerclient/external/github.com/Sirupsen/logrus/terminal_freebsd.go:12: Termios redeclared in this block
        previous declaration at Godeps/_workspace/src/github.com/fsouza/go-dockerclient/external/github.com/Sirupsen/logrus/terminal_bsd.go:9
godep: go exit status 2
Makefile:9: recipe for target 'build' failed
gmake: *** [build] Error 1

# go version
go version go1.5.1 freebsd/amd64

# uname -a
FreeBSD node 10.2-STABLE FreeBSD 10.2-STABLE #11 r289763: Thu Oct 22 23:30:25 CEST 2015 node:/usr/obj/usr/src/sys/GENERIC  amd64

```

**Comment by MerlinDMC** [comment]
That is due to the fact that the dependency gosigar has no FreeBSD support.

It is mainly using the proc filesystem to parse cpu stats which in FreeBSD is not available.
You probably want to extend gosigar to support FreeBSD in the first place which would mean getting a `sigar_freebsd.go` in there that implements the missing bits of all those types - mainly all the Get methods.
If you take `sigar_linux.go` as a source and reimplement the stat gathering for the FreeBSD world you would be good.

**Comment by sparrc** [comment]
I think it would be more simple to just remove the go-sigar dependency and replace it with gopsutil. gosigar is a project that doesn't often respond to PRs, and I think you even have to send in a snail-mail CLA agreement

**Comment by MerlinDMC** [comment]
@sparrc since gopsutil is already a dependency for other stuff this seems to be a good way.
There still is the termios problem in the logrus code but @Sirupsen is very responsive so that problem might be easily solved.

**Comment by MerlinDMC** [comment]
Turns out it already is fixed in logrus just the stored version of go-dockerclient still had a broken version.
A simple bump of `github.com/fsouza/go-dockerclient` via godep did the trick.

PR #372 should fix compilation on FreeBSD

**Comment by sparrc** [comment]
fixed by https://github.com/influxdb/telegraf/pull/372

**Comment by rickard-von-essen** [comment]
@syepes @cornerot FYI: Telegraf now support ZFS on FreeBSD since #1224.
