### ISSUE TITLE
[0.2.0] - Jolokia plugin not available in 0.2.0

### ISSUE THREAD

**Issue by JulienChampseix** [influxdb/telegraf#358]
Hi Team,

We wanted to test jolokia from the latest version of telegraf 0.2.0 (http://get.influxdb.org/telegraf/telegraf_0.2.0_amd64.deb) but apparently dont work : 

root@-:/opt/telegraf# ./telegraf -usage jolokia
___Plugin jolokia not found and Output jolokia not found___
root@-:/opt/telegraf# ./telegraf -version
___Telegraf - Version 0.2.0___

It's weird because on the main page in section Supported Plugins, it appear as available.

Can you check ?

**Comment by panda87** [comment]
This will be available in the next version, 0.2.1
Someone knows when this version will be released since I also want to test the Jolokia plugin.

Thanks

**Comment by sparrc** [comment]
Jolokia will be available in 0.2.1, sorry for the confusion,

I can make a 0.2.1 release this Thursday

**Comment by panda87** [comment]
Sounds good :+1: 
There are nightly builds in Telegraf?

**Comment by JulienChampseix** [comment]
@sparrc that will be great !!! if you can do this release :+1:

**Comment by sparrc** [comment]
@panda87 Currently there are not nightly builds for Telegraf but I'm hoping to get that going soon

**Comment by JulienChampseix** [comment]
@sparrc i saw 0.2.1 is not out last Thursday, is it planned this week ?

**Comment by sparrc** [comment]
@JulienChampseix I'll have it packaged and on the github page by this evening (US PST)
