### ISSUE TITLE
Installing together telegraf-0.1.1-1.x86_64.rpm and influxdb-0.9.0-1.x86_64.rpm

### ISSUE THREAD

**Issue by luinav** [influxdb/telegraf#36]
In a Centos 7 host I have installed the Influxdb package first and then the telegraf package.

The telegraf package overwrites the startup script of influxdb "/opt/influxdb/init.sh".
In the /etc/init.d both links are pointing to the same file:

lrwxrwxrwx.  1 root root    21 jul  1 15:00 influxdb -> /opt/influxdb/init.sh
lrwxrwxrwx.  1 root root    21 jul  1 15:06 telegraf -> /opt/influxdb/init.sh

The consequence is that installing the telegraph package breaks the influxdb startup scripts

**Comment by toddboom** [comment]
@luinav this should be resolved in `v0.1.2`, but a few changes in the `init.sh` didn't get made, but those will be fixed in `v0.1.3`.
