### ISSUE TITLE
influxdb and telegraf conflicting for ownership of /var/run/influxdb/ directory

### ISSUE THREAD

**Issue by jimconner** [influxdb/telegraf#37]
Installing both influxdb and telegraf on the same host results in one or the other failing to start correctly from the init.d scripts (on Ubuntu)

The problem seems to be down to the ownership of the /var/run/influxdb directory - If influx is installed first, then the directory will be owned by influxdb:influxdb and the telegraf:telegraf user is not able to write a pid file into there and the daemon fails to start. If the packages are installed in the opposite order, then the telegraf user will own the dir and influx will fail to start. 

It's not a hard problem to work around, but it would be nice if the two packages did not conflict with each other.

**Comment by pkkummermo** [comment]
+1 For this

**Comment by luinav** [comment]
+1 I think this package conflict is the same as  #36

**Comment by dennisjac** [comment]
Telegraf should use it's own unique namespace e.g. /opt/telegraf and /var/run/telegraf. Is see no good reason why it should share directories with influxdb.

**Comment by toddboom** [comment]
i mentioned this also in #36 - this should be resolved in v0.1.2, but a few changes in the init.sh didn't get made, but those will be fixed in v0.1.3.
