### ISSUE TITLE
Support sending metrics to Kafka

### ISSUE THREAD

**Issue by pauldix** [influxdb/telegraf#38]
We should be able to send metrics to a variety of places other than InfluxDB. This means that we'll need to have some sort of framework for defining new output sinks. This also means that we should be able to disable sending metrics to any of these output sinks, including InfluxDB.

What I'm thinking is to pull the InfluxDB settings into another area like `outputs`. Then, like plugins, define a number of different outputs where metrics can be sent to.

For Kafka, we should send metrics using the line protocol. This should be fairly simply using the InfluxDB client to convert the metrics to their line protocol equivalents.

The work to add support for Riemann (#34) will also need this output sink implementation.

**Comment by vic3lord** [comment]
:+1:

**Comment by jipperinbham** [comment]
:+1: 

Has work started on this or are you looking for some help/ideas?

In another project similar to this, we use In/Out channels to wire up the message communication and defined a standard Msg struct to be passed along. It seems to work well for that project so didn't know if something similar would be good here as well.

**Comment by pauldix** [comment]
We haven't started work on this and are definitely looking for help. We want to be able to to output to one or more output sinks like Kafka or InfluxDB or Riemann

**Comment by steverweber** [comment]
some help perhaps:
https://github.com/mozilla-services/heka/blob/31a1bf9a1ad080e3ec8ec71ff3cefccdb609dc09/plugins/kafka/kafka_output.go
