### ISSUE TITLE
Prometheus error in test-short

### ISSUE THREAD

**Issue by gotyaoi** [influxdb/telegraf#385]
Getting the following error when running `make test-short`:
```
--- FAIL: TestPrometheusWritePointEmptyTag (0.00s)
        Error Trace:    prometheus_client_test.go:46
        Error:          No error is expected but got error making HTTP request to http://localhost:9126/metrics: Get http://localhost:9126/metrics: dial tcp 127.0.0.1:9126: getsockopt: connection refused

FAIL
FAIL    github.com/influxdb/telegraf/outputs/prometheus_client  0.035s
```
Not sure if this is a dependency issue or if this test should not be in test-short.

**Comment by oldmantaiter** [comment]
@gotyaoi There were issues initially with the testing as the prometheus_client starts its own "service", I believe @sparrc fixed up the tests but I can take another look.

Is this happening every time you run test-short?
