### ISSUE TITLE
Stops sending data after "Error: current total CPU time is less than previous total CPU time"

### ISSUE THREAD

**Issue by kohlerm** [influxdb/telegraf#388]
Telegraf stops sending data after getting into the 
"Error: current total CPU time is less than previous total CPU time". 
Not sure how it happened, but restarting telegraf solved the issue.

Not that I monitored a laptop for testing purposes, which might not have connection to the server all the times, and might also be hibernated and restarted. 

Anyway it would be good if there would be a better solution then not sending any data anymore.

**Comment by sparrc** [comment]
Thanks for the report @kohlerm, I have a fix in-hand for this and it will be available in release 0.2.4

**Comment by kohlerm** [comment]
great! Will let you know whether it worked for me!
