### ISSUE TITLE
Ability to add a tag specifying the plugin that captured the metric

### ISSUE THREAD

**Issue by haninaguib** [influxdb/telegraf#393]
I just started looking at telegraf, so forgive me if this functionality already exits.

In my use case having a tag that tells me which plugin captured the metric would be very useful, for 
filtering and analyzing the data.

**Comment by haninaguib** [comment]
Just noticed that metric names seem to be prefixed with plugin name. This will probably be enough for my use case.

**Comment by sparrc** [comment]
@haninaguib This will be even more clear once we make this change: #152, which will aggregate measurements into a single measurement, named by the plugin.
