### ISSUE TITLE
Wrong/changed datatype for metrics

### ISSUE THREAD

**Issue by oyvindt** [influxdb/telegraf#429]
I have telegraf 0.2.3 running on some machines writing data to InfluxDB (version 0.9.5.1) . Added a new machine now to this system with telegraf 0.2.4, and it's unable to write data to InfluxDB with this error:

ERROR: write failed: field type conflict: input field "value" on measurement "system_uptime" is type float64, already exists as type integer

**Comment by sparrc** [comment]
This was actually changed because in Telegraf 0.2.2 and prior we were writing it as a float, this was a bug that came up because of FreeBSD support, see #390 

It's going to stay a float, sorry for the inconvenience
