### ISSUE TITLE
Bandwidth consumption

### ISSUE THREAD

**Issue by ddes** [influxdb/telegraf#431]
Hi guys,

I'm trying to get the bandwidth usage via telegraf net plugin but when I choose "net_bytes_revc", I receive results like 370GBps which seems to be cumulated.

Is there a way to have the usage in realtime per interface ?

I specified this in my config:

> [net]
   interfaces = ["eth0"]

**Comment by sparrc** [comment]
to get a per-second rate of consumption you should use the influxdb derivative functions
https://influxdb.com/docs/v0.9/query_language/functions.html#derivative

**Comment by JulienChampseix** [comment]
@ddes +1

@sparrc Looks like this question could be really usefull for the community (plus added in documentation as example). If you could provide an example of request (select) which could return the right informations (here the bandwidth consumption for in & out), that will be perfect.

**Comment by sparrc** [comment]
@JulienChampseix currently working on 0.3.0, where the doc will need to be re-written to accomodate the new db schema coming.....PRs for code AND docs are always welcome, especially docs ;-)

**Comment by lifeofguenter** [comment]
I'd be happy to get some info on this as well. To me it is much more significant how high the bandwidth is as opposed to the bytes transferred, as the bandwidth will give me a clear and fast indication of hardware or contract limitations.

**Comment by JulienChampseix** [comment]
@sparrc any news on this request ? for get the bandwidth not cumulated infos

**Comment by sparrc** [comment]
I'm sorry but I really don't have time to write docs about InfluxDB query specifics. PRs are welcome but that's the best I can do.
