### ISSUE TITLE
Telegraf not uptodate in InfluxDB yum/apt repos

### ISSUE THREAD

**Issue by allen13** [influxdb/telegraf#433]
The new influxdb repository does not seem to be keeping up to date with the latest telegraf releases.
https://repos.influxdata.com/centos/7/x86_64/stable/

**Comment by sparrc** [comment]
@rossmcdonald any ideas? What do we need to do to keep Telegraf updated in these repos?

**Comment by rossmcdonald** [comment]
Sorry about that! I haven't been keeping up to date with the most recent Telegraf releases. It should be fixed now.

@sparrc We're going to try and implement some automated way of keeping the releases up-to-date, but, in the meantime, just ping me when there's a new release and I'll get it added.

**Comment by gfk** [comment]
Hi Ross, telegraf 0.10 has been released a couple days ago, could you add it to the repos? Thanks! 
https://influxdata.com/blog/announcing-telegraf-0-10-0/

**Comment by sparrc** [comment]
@gfk, 0.10 is a breaking build, which is why we're holding off on updating.

**Comment by rossmcdonald** [comment]
@gfk The 0.10.0 packages are now available through the repository.
