### ISSUE TITLE
[tags] are not attached to metrics

### ISSUE THREAD

**Issue by f0s0** [influxdb/telegraf#434]
I have tags like this in Telegraf configuration:

[tags]
apache = "1"
phpfpm = "1"

Configuration is parsed correctly. Metrics from different plugins are written to InfluxDB output but no custom tags are found within the metrics.
In addition, it would be useful to be able to specify tags on a plugin basis.
I am running Telegraf 0.2.2 with InfluxDB 0.9.5.1

**Comment by sparrc** [comment]
@f0s0 please specify your version

**Comment by sparrc** [comment]
@f0s0 This was a bug in 0.2.2, it is fixed in the latest version (0.2.4), sorry for the inconvenience!
