### ISSUE TITLE
Mysql plugin should show slave status

### ISSUE THREAD

**Issue by tarjei** [influxdb/telegraf#459]
Hi, the mysql plugin is missing the crucial Slave status information. 
@see: 
https://github.com/prometheus/mysqld_exporter/blob/master/mysqld_exporter.go#L49

**Comment by sparrc** [comment]
thanks for the report @tarjei, but I'm going to close this in favor of https://github.com/influxdb/telegraf/issues/403, as I'm fairly certain that PR will include slave status

**Comment by tarjei** [comment]
Cool!
23. des. 2015 3.07 a.m. skrev "Cameron Sparr" <notifications@github.com>:
