### ISSUE TITLE
issue with reading kafka mesages in telegraf to be written to influxdb

### ISSUE THREAD

**Issue by iotp** [influxdb/telegraf#468]
I am trying to read messages from kafka and all my messages fail as follows: 
(note - i am using collectd to write the data to kafka)

2015/12/28 20:55:16 Could not parse kafka message: [{"values":[0],"dstypes":["gauge"],"dsnames":["value"],"time":1451357716.011,"interval":10.000,"host":"remotemachine","plugin":"disk","plugin_instance":"mmcblk0p1","type":"pending_operations","type_instance":""}], error: unable to parse '[{"values":[0],"dstypes":["gauge"],"dsnames":["value"],"time":1451357716.011,"interval":10.000,"host":"remotemachine","plugin":"disk","plugin_instance":"mmcblk0p1","type":"pending_operations","type_instance":""}]': missing tag value

**Comment by sparrc** [comment]
The kafka messages need to be in [line protocol](https://docs.influxdata.com/influxdb/v0.9/write_protocols/line/) format for the `kafka_consumer` plugin to read them
