### ISSUE TITLE
advantages of telegraf over heka

### ISSUE THREAD

**Issue by steverweber** [influxdb/telegraf#48]
telegraf seems to have good overlap with heka:
https://github.com/mozilla-services/heka

heka seems to have the InfluxDB 0.9.x+ line protocol almost complete.
https://github.com/mozilla-services/heka/pull/1574
https://github.com/mozilla-services/heka/pull/1595

what is the advantage of telegraf over heka?
Perhaps it would be nice to include that information in the readme.

thanks.

**Comment by marcosnils** [comment]
Interesting. I'd like to hear @otoolep and @pauldix opinion about this. 

My first guessing is that telegraf is good for storing things from multiple sources into InfluxDB whether Heka seems like a generic processor from multiple inputs and outputs. This seems like a constraint because all metrics telegraf collects are optimized for Influx features (batching, tags & cq's mainly).

Anyway's it's just my assumption.

**Comment by otoolep** [comment]
I don't know much about Heka, so can't really comment. Telegraf doesn't store data per-se, but is mostly for writing data to InfluxDB, collected from various sources. Of course, it's much newer than Heka.

**Comment by steverweber** [comment]
http://hekad.readthedocs.org/en/v0.10.0b0/
/perhaps its worth a closer look/ lessons learned in heka could likely help telegraf.

**Comment by steverweber** [comment]
I think i'll reopen this because some good code is in heka,  A review of heka will likely help this project!

For example telegraf might like to investigate the generic logstreamer.
https://hekad.readthedocs.org/en/v0.9.2/pluginconfig/logstreamer.html#logstreamerplugin

https://github.com/mozilla-services/heka/tree/dev/plugins
https://github.com/mozilla-services/heka/tree/dev/logstreamer

cheers

**Comment by sparrc** [comment]
It's true that there is a lot of overlap between Heka and telegraf, I would also agree that some of their plugins (especially logstreamer & statsd) could be integrated in a similar fashion into telegraf.

That being said, I'm going to close this issue and instead open a new issue for making a plugin similar to the logstreamer, as we already have an open issue for making a statsd-style aggregator.
