### ISSUE TITLE
1000+ series per host causes slow performance in influxdb

### ISSUE THREAD

**Issue by jhofeditz** [influxdb/telegraf#61]
I'm running a test using influxdb 9.2 nightly and telegraf 0.1.3 on a single host with SSD. I am sending metrics from 500 hosts to influxdb using telegraf's default plugins and config. Within a week, influxdb begins returning 500 timeout errors to all requests. The database size is 340G with 137,269 unique series.

In https://influxdb.com/docs/v0.9/concepts/schema_and_data_layout.html, it mentions keeping tag cardinality <100k so I dug in to see where all of the tags are coming from. Each VM host sends about 150 series while a physical hypervisor sends over 1000.

Here is the breakdown from one physical server:
disk metrics: 180 (6 metrics * 30 paths)
cpu metrics: 352 (11 data points * 32 cores)
io metrics: 378 (7 metrics * 54 disk partitions)
net metrics: 128 (8 metrics * 16 interfaces)
load/swap metrics: 9

Here is the best case result (with filtering and CPU aggregation):
disk metrics: 48 (6 metrics * 8 paths)
cpu metrics: 11 (11 data points * 1 aggregate cpu value)
io metrics: 378 (7 metrics * 16 disks in iostat)
net metrics: 128 (8 metrics * 16 interfaces)
load/swap metrics: 9

The same update of a VM host reduces the per host metric count from 146 to 50. The doc says "As a rule of thumb, keep tag cardinality below 100,000. " With 1000 series per host, that is at most 100 servers. Even the low end, 50 metrics per host only allows around 2,000 servers. Is this a limitation that can be addressed in telegraf or influxdb?

I love the simplicity and drop-in nature of the telegraf/influxdb/grafana stack. But the system needs to be able to scale out of the box. Multiple databases would make grafana more complex but it might be an short term solution. Is there a better way?

**Comment by otoolep** [comment]
@jhofeditz -- can we see your InfluxDB config file?

**Comment by jhofeditz** [comment]
https://gist.github.com/jhofeditz/934d8e7f296be1501707

**Comment by jhofeditz** [comment]
Re-reading the schema and data layout page, is the limit referring to the number of unique values per tag (host=) or the total number of unique tag series (host=,name=,serial=)? My maximum unique values per tag is only around 5,000. 

If having >100,000 series is ok, then this is a InfluxDB issue and I'll open the issue there.

**Comment by jhofeditz** [comment]
D'oh! I might need to change the subject to "telegraf running 100x on one host causes slow performance" :fearful: It turns out that on one server puppet was spawning lots of telegraf clients because /etc/init.d/telegraf status said that telegraf was stopped.

We'll watch to make sure that doesn't happen again. We wiped the database and are now going to give things another week to see how it performs. Sorry about the false alarm.

I would still like to know if the number of metrics is going to impact influxdb at scale, but this specific issue seems to be unrelated. Thanks!
