### ISSUE TITLE
not reinventing the wheel

### ISSUE THREAD

**Issue by schmurfy** [influxdb/telegraf#66]
If that is something that you are interested in there is already a nice library called sigar which is cross platform and provide most of the system data: cpu, memory, network interfaces, processes, ...
( https://github.com/hyperic/sigar )

I currently use it successfully for a similar project on:
- FreeBSD
- Linux
- OpenBSD
- Illumos (not entirely)

(it also supports Mac OS X, my development server)

**Comment by schmurfy** [comment]
nevermind, that's GPL... 
God I hate this license.

**Comment by schmurfy** [comment]
.. or not, they switched to apache so it can be used.

**Comment by sparrc** [comment]
@schmurfy I don't think that this fits as an "issue", the purpose of telegraf is to be a Go implementation of different services logging into InfluxDB (or other outputs). From what I can tell, sigar doesn't replace telegraf, and there's no reason they can't run side-by-side.

**Comment by schmurfy** [comment]
you completely missed the point... Have you looked at it ? The point of sigar would be to provide you the system data (cpu, ram, network usage, ...), not to replace your project or else there would indeed be no point in my issue.

libsigar by itself does one thing: collect data, that is all.
I posted this because too many projects code again and again and again these part and but I don't really care what road you take (and I doubt you will support all the OSes it supports anytime soon).

**Comment by sparrc** [comment]
I believe what you're suggesting is replacing gopsutil: https://github.com/influxdb/telegraf/tree/master/plugins/system/ps with a third-party application that does not provide native go bindings. I'm not sure I see the benefit of what you're getting at, but would be happy to review a PR if you feel strongly that this would be a better system :-)

**Comment by schmurfy** [comment]
Yes I missed it, they are similar, the way projects dependencies are handled in pretty chaotic ;)
