### ISSUE TITLE
Add logrotate script for telegraf.log to rpm/deb packaging

### ISSUE THREAD

**Issue by jhofeditz** [influxdb/telegraf#67]
something like this in /etc/logrotate.d/telegraf would work for redhat/centos (rotating weekly, keep for a month):
    /var/log/telegraf/telegraf.log {
        missingok
        nocreate
        postrotate
	    /sbin/service telegraf restart  > /dev/null 2>/dev/null || true
        endscript
    }

**Comment by srfraser** [comment]
Added https://github.com/influxdb/telegraf/pull/87 before spotting this. Either file would be good.
