### ISSUE TITLE
redis servers is not tagged to multiple ports

### ISSUE THREAD

**Issue by kotopes** [influxdb/telegraf#74]
in config:
[redis]

servers = ["10.0.0.13:6386", "10.0.0.13:6380", "10.0.0.13:6381", "10.0.0.13:6382", "10.0.0.13:6383", "10.0.0.13:6384", "10.0.0.13:6385"]

------------------------------------
in influx 0.9.1:
>show measurements
...
redis_total_commands_processed
...

>select * from redis_total_commands_processed
....
name: redis_total_commands_processed
tags: host=wpr01
time                            value
----                            -----
2015-07-22T11:31:32.905606408Z  2387730910
2015-07-22T11:31:37.909249167Z  2387738534
2015-07-22T11:31:42.907242355Z  2387746082
....

where i see in tags "port: 6380(6381...6386)" ?

**Comment by kotopes** [comment]
i add code before tags:

		_, rPort, err := net.SplitHostPort(addr.Host)
		if err != nil {
			rPort = defaultPort
		}
		tags := map[string]string{"host": addr.String(), "port": rPort}

**Comment by sparrc** [comment]
@kotopes I believe this can now be closed due to closing the pull request, let me know if there are any more problems!
