### ISSUE TITLE
[feature request] On launch telegraf should create `telegraf` database if it doesn't already

### ISSUE THREAD

**Issue by mjdesa** [influxdb/telegraf#77]
Currently the user has to create a `telegraf` database manually. The tool should do this for us.

**Comment by toddboom** [comment]
+1

**Comment by sparrc** [comment]
see commit https://github.com/influxdb/telegraf/commit/c0cef8ca43b3d7dcf1e0235ac8aff9db5e9c8183

**Comment by alvaromorales** [comment]
Should the db name be configurable?

I've been running telegraf 1.4 and writing metrics to a database that's not named `telegraf`. If I upgrade to the next version, I'm going to have to migrate all my data to a new db. Happy to PR

**Comment by sparrc** [comment]
@alvaromorales yes, it should be, I'll fix that now

**Comment by codeb2cc** [comment]
I think there's should be an option to disable this feature. 3c7c8926fb436e683c6a74201b1c90f390ef419f added a default error "Could not create database on any server" and if the creation query failed, telegraf exists. In my case, the influxdb user for telegraf has no right to create db and the creation query gets a 401 response.

**Comment by sparrc** [comment]
@codeb2cc please open a new issue for that
