### ISSUE TITLE
Add Docker labels as tags.

### ISSUE THREAD

**Issue by ajohnstone** [influxdb/telegraf#90]
With  telegraf it only supports tags in the form of id, name and command.
However doesn't import the actual labels associated to the container. 

https://docs.docker.com/userguide/labels-custom-metadata/.

This is quite important with things like ECS.

**Comment by sparrc** [comment]
Sounds good, will investigate

**Comment by JulienChampseix** [comment]
Will be usefull this feature because labels are really usefull in docker. Do you progress on this enhancement ?

**Comment by sparrc** [comment]
I haven't yet, as I've been working on merging PRs and other more basic stability issues with Telegraf.

**Comment by zepouet** [comment]
Hello, I will try to do it because I worked with the docker api few times ago.

**Comment by JulienChampseix** [comment]
any progress on it ?

**Comment by sparrc** [comment]
I will be able to work on this soon, once I can get #180 merged (waiting on CLA)

**Comment by JulienChampseix** [comment]
Cool the #180 is now close, hope the merge will come soon for unblock this issue/feature

**Comment by sparrc** [comment]
@JulienChampseix finally found some time to get to this, it's available if you build from source, and I'll hopefully get a nightly build system going soon to get features like this out to people sooner
