### ISSUE TITLE
Unable to package telegraf due to missing logrotate -- cp: cannot stat ‘etc/logrotate.d/telegraf’: No such file or directory

### ISSUE THREAD

**Issue by ajohnstone** [influxdb/telegraf#95]
```
$ go get -u github.com/influxdb/telegraf/...
$ cd $GOPATH/src/github.com/influxdb/telegraf
$ ./package.sh 1

Starting package process...

/home/andrew/.gvm/bin/gvm
Now using version go1.4.2
GOPATH (/home/andrew/.gvm/pkgsets/go1.4.2/global) looks sane, using /home/andrew/.gvm/pkgsets/go1.4.2/global for installation.
Git tree is clean.
From https://github.com/influxdb/telegraf
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Git tree updated successfully.
Build completed successfully.
telegraf copied to /tmp/tmp.MgYgIBqRvH//opt/telegraf/versions/1
scripts/init.sh copied to /tmp/tmp.MgYgIBqRvH//opt/telegraf/versions/1/scripts
cp: cannot stat ‘etc/logrotate.d/telegraf’: No such file or directory
Failed to copy etc/logrotate.d/telegraf to packaging directory -- aborting.
```

**Comment by sparrc** [comment]
@srfraser can you comment on this? I believe it might be related to PR #87

**Comment by sparrc** [comment]
looks like PR #87 wasn't complete, we shouldn't have merged that, I'm going to create a new PR to revert it

**Comment by srfraser** [comment]
Apologies, I must have missed the actual logrotate config file - it's in my own copy. A simple option would be to add etc/logrotate.d/telegraf, containing something like

/var/log/telegraf/telegraf.log
{
        rotate 6
        daily
        missingok
            notifempty
            compress
    }

**Comment by sparrc** [comment]
no problem @srfraser, my fault for merging it, if you want to send up another PR with the necessary file I'd be happy to re-merge it!
