### ISSUE TITLE
update integer output to new line protocol format

### ISSUE THREAD

**Issue by beckettsean** [influxdb/telegraf#99]
With 0.9.3, the line protocol has changed for integers: https://github.com/influxdb/influxdb/pull/3526

This change means that current telegraf users who upgrade to 0.9.3 cannot write a number of values, because they are integer fields in the db but the current telegraf sends them without the trailing `i`, meaning they parse as floats. That causes a type mismatch and a write failure.

**Comment by beckettsean** [comment]
https://github.com/influxdb/influxdb/issues/3589 for the relevant issue

**Comment by sparrc** [comment]
To summarize an email thread, this will simply require a re-build of telegraf using the 0.9.3 release of InfluxDB.

Currently the head of influxdb will not work with telegraf unless you build it from source.

**Comment by sparrc** [comment]
closing this out because it should be fixed with any newer build of telegraf

**Comment by beckettsean** [comment]
@sparrc is there a plan to issue new telegraf builds in conjunction with new influxdb builds?

**Comment by sparrc** [comment]
@beckettsean Not at the moment, but the CircleCI job is now building binaries as well as .deb and .rpm files, so one can find an updated package there if need be https://circleci.com/gh/influxdb/telegraf/tree/master

I believe that it was decided that Telegraf would release on it's own schedule unless there was a release of another product (such as InfluxDB) that introduced a breaking change.

**Comment by beckettsean** [comment]
> I believe that it was decided that Telegraf would release on it's own schedule unless there was a release of another product (such as InfluxDB) that introduced a breaking change.

@sparrc I agree with and support the decision about releases in general, but this issue was about a specific case of the "breaking change" mentioned. I would like to know that we will have a coordinated release of telegraf and InfluxDB with the integer write change. An issue seems like a good place to track that so we don't forget on launch day.

**Comment by sparrc** [comment]
@beckettsean fair enough, I'll keep it open

**Comment by sparrc** [comment]
This is fixed and ready in 0.1.5
